In [1]:
import numpy as np
import pandas as pd
import gc
import time
from contextlib import contextmanager
import lightgbm as lgb
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.model_selection import KFold, StratifiedKFold
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [4]:
def one_hot_encoder(df, nan_as_category = True):
    original_columns = list(df.columns)
    categorical_columns = [col for col in df.columns if df[col].dtype == 'object']
    df = pd.get_dummies(df, columns= categorical_columns, dummy_na= nan_as_category)
    new_columns = [c for c in df.columns if c not in original_columns]
    return df, new_columns

In [4]:
bureau = pd.read_csv('../input/bureau.csv', nrows = None)
bb = pd.read_csv('../input/bureau_balance.csv', nrows = None)

In [5]:
bb, bb_cat = one_hot_encoder(bb, True)

In [6]:
bb

,SK_ID_BUREAU,MONTHS_BALANCE,STATUS_0,STATUS_1,STATUS_2,STATUS_3,STATUS_4,STATUS_5,STATUS_C,STATUS_X,STATUS_nan
0,5715448,0,0,0,0,0,0,0,1,0,0
1,5715448,-1,0,0,0,0,0,0,1,0,0
2,5715448,-2,0,0,0,0,0,0,1,0,0
3,5715448,-3,0,0,0,0,0,0,1,0,0
4,5715448,-4,0,0,0,0,0,0,1,0,0
5,5715448,-5,0,0,0,0,0,0,1,0,0
6,5715448,-6,0,0,0,0,0,0,1,0,0
7,5715448,-7,0,0,0,0,0,0,1,0,0
8,5715448,-8,0,0,0,0,0,0,1,0,0
9,5715448,-9,1,0,0,0,0,0,0,0,0
10,5715448,-10,1,0,0,0,0,0,0,0,0
11,5715448,-11,0,0,0,0,0,0,0,1,0
12,5715448,-12,0,0,0,0,0,0,0,1,0
13,5715448,-13,0,0,0,0,0,0,0,1,0
14,5715448,-14,1,0,0,0,0,0,0,0,0
15,5715448,-15,1,0,0,0,0,0,0,0,0
16,5715448,-16,1,0,0,0,0,0,0,0,0
17,5715448,-17,1,0,0,0,0,0,0,0,0
18,5715448,-18,1,0,0,0,0,0,0,0,0
19,5715448,-19,1,0,0,0,0,0,0,0,0
20,5715448,-20,0,0,0,0,0,0,0,1,0
21,5715448,-21,0,0,0,0,0,0,0,1,0
22,5715448,-22,0,0,0,0,0,0,0,1,0
23,5715448,-23,0,0,0,0,0,0,0,1,0
24,5715448,-24,0,0,0,0,0,0,0,1,0
25,5715448,-25,0,0,0,0,0,0,0,1,0
26,5715448,-26,0,0,0,0,0,0,0,1,0
27,5715449,0,0,0,0,0,0,0,1,0,0
28,5715449,-1,0,0,0,0,0,0,1,0,0
29,5715449,-2,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
27299895,5041332,-18,0,0,0,0,0,0,0,1,0
27299896,5041332,-19,0,0,0,0,0,0,0,1,0
27299897,5041332,-20,0,0,0,0,0,0,0,1,0
27299898,5041332,-21,0,0,0,0,0,0,0,1,0
27299899,5041332,-22,0,0,0,0,0,0,0,1,0
27299900,5041332,-23,0,0,0,0,0,0,0,1,0
27299901,5041336,-28,0,0,0,0,0,0,0,1,0
27299902,5041336,-29,0,0,0,0,0,0,0,1,0
27299903,5041336,-30,0,0,0,0,0,0,0,1,0
27299904,5041336,-31,0,0,0,0,0,0,0,1,0
27299905,5041336,-32,0,0,0,0,0,0,0,1,0
27299906,5041336,-33,0,0,0,0,0,0,0,1,0
27299907,5041336,-34,0,0,0,0,0,0,0,1,0
27299908,5041336,-35,0,0,0,0,0,0,0,1,0
27299909,5041336,-36,0,0,0,0,0,0,0,1,0
27299910,5041336,-37,0,0,0,0,0,0,0,1,0
27299911,5041336,-38,0,0,0,0,0,0,0,1,0
27299912,5041336,-39,0,0,0,0,0,0,0,1,0
27299913,5041336,-40,0,0,0,0,0,0,0,1,0
27299914,5041336,-41,0,0,0,0,0,0,0,1,0
27299915,5041336,-42,0,0,0,0,0,0,0,1,0
27299916,5041336,-43,0,0,0,0,0,0,0,1,0
27299917,5041336,-44,0,0,0,0,0,0,0,1,0
27299918,5041336,-45,0,0,0,0,0,0,0,1,0
27299919,5041336,-46,0,0,0,0,0,0,0,1,0
27299920,5041336,-47,0,0,0,0,0,0,0,1,0
27299921,5041336,-48,0,0,0,0,0,0,0,1,0
27299922,5041336,-49,0,0,0,0,0,0,0,1,0
27299923,5041336,-50,0,0,0,0,0,0,0,1,0
27299924,5041336,-51,0,0,0,0,0,0,0,1,0

In [7]:
bb_cat

['STATUS_0',
 'STATUS_1',
 'STATUS_2',
 'STATUS_3',
 'STATUS_4',
 'STATUS_5',
 'STATUS_C',
 'STATUS_X',
 'STATUS_nan']

In [9]:
#original_columns = list(bureau.columns)

In [10]:
#original_columns

In [11]:
#categorical_columns = [col for col in bureau.columns if bureau[col].dtype == 'object']

In [12]:
#categorical_columns

In [13]:
#bureau = pd.get_dummies(bureau, columns= categorical_columns, dummy_na= True)

In [14]:
#bureau

In [15]:
#bureau_cat = [c for c in bureau.columns if c not in original_columns]

In [16]:
#bureau_cat

In [8]:
bureau, bureau_cat = one_hot_encoder(bureau, True)

In [9]:
bureau_cat

['CREDIT_ACTIVE_Active',
 'CREDIT_ACTIVE_Bad debt',
 'CREDIT_ACTIVE_Closed',
 'CREDIT_ACTIVE_Sold',
 'CREDIT_ACTIVE_nan',
 'CREDIT_CURRENCY_currency 1',
 'CREDIT_CURRENCY_currency 2',
 'CREDIT_CURRENCY_currency 3',
 'CREDIT_CURRENCY_currency 4',
 'CREDIT_CURRENCY_nan',
 'CREDIT_TYPE_Another type of loan',
 'CREDIT_TYPE_Car loan',
 'CREDIT_TYPE_Cash loan (non-earmarked)',
 'CREDIT_TYPE_Consumer credit',
 'CREDIT_TYPE_Credit card',
 'CREDIT_TYPE_Interbank credit',
 'CREDIT_TYPE_Loan for business development',
 'CREDIT_TYPE_Loan for purchase of shares (margin lending)',
 'CREDIT_TYPE_Loan for the purchase of equipment',
 'CREDIT_TYPE_Loan for working capital replenishment',
 'CREDIT_TYPE_Microloan',
 'CREDIT_TYPE_Mobile operator loan',
 'CREDIT_TYPE_Mortgage',
 'CREDIT_TYPE_Real estate loan',
 'CREDIT_TYPE_Unknown type of loan',
 'CREDIT_TYPE_nan']

In [10]:
bureau

,SK_ID_CURR,SK_ID_BUREAU,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,...,CREDIT_TYPE_Loan for business development,CREDIT_TYPE_Loan for purchase of shares (margin lending),CREDIT_TYPE_Loan for the purchase of equipment,CREDIT_TYPE_Loan for working capital replenishment,CREDIT_TYPE_Microloan,CREDIT_TYPE_Mobile operator loan,CREDIT_TYPE_Mortgage,CREDIT_TYPE_Real estate loan,CREDIT_TYPE_Unknown type of loan,CREDIT_TYPE_nan
0,215354,5714462,-497,0,-153.0,-153.0,NaN,0,91323.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1,215354,5714463,-208,0,1075.0,NaN,NaN,0,225000.000,171342.000,...,0,0,0,0,0,0,0,0,0,0
2,215354,5714464,-203,0,528.0,NaN,NaN,0,464323.500,NaN,...,0,0,0,0,0,0,0,0,0,0
3,215354,5714465,-203,0,NaN,NaN,NaN,0,90000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
4,215354,5714466,-629,0,1197.0,NaN,77674.500,0,2700000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
5,215354,5714467,-273,0,27460.0,NaN,0.000,0,180000.000,71017.380,...,0,0,0,0,0,0,0,0,0,0
6,215354,5714468,-43,0,79.0,NaN,0.000,0,42103.800,42103.800,...,0,0,0,0,0,0,0,0,0,0
7,162297,5714469,-1896,0,-1684.0,-1710.0,14985.000,0,76878.450,0.000,...,0,0,0,0,0,0,0,0,0,0
8,162297,5714470,-1146,0,-811.0,-840.0,0.000,0,103007.700,0.000,...,0,0,0,0,0,0,0,0,0,0
9,162297,5714471,-1146,0,-484.0,NaN,0.000,0,4500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
10,162297,5714472,-1146,0,-180.0,NaN,0.000,0,337500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
11,162297,5714473,-2456,0,-629.0,-825.0,NaN,0,675000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
12,162297,5714474,-277,0,5261.0,NaN,0.000,0,7033500.000,NaN,...,0,0,0,0,0,0,1,0,0,0
13,402440,5714475,-96,0,269.0,NaN,0.000,0,89910.000,76905.000,...,0,0,0,0,0,0,0,0,0,0
14,238881,5714482,-318,0,-187.0,-187.0,NaN,0,0.000,0.000,...,0,0,0,0,0,0,0,0,0,0
15,238881,5714484,-2911,0,-2607.0,-2604.0,NaN,0,48555.000,NaN,...,0,0,0,0,0,0,0,0,0,0
16,238881,5714485,-2148,0,-1595.0,-987.0,NaN,0,135000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
17,238881,5714486,-381,0,NaN,NaN,NaN,0,450000.000,520920.000,...,0,0,0,0,0,0,0,0,0,0
18,238881,5714487,-95,0,1720.0,NaN,NaN,0,67500.000,8131.500,...,0,0,0,0,0,0,0,0,0,0
19,238881,5714488,-444,0,-77.0,-77.0,0.000,0,107184.060,0.000,...,0,0,0,0,0,0,0,0,0,0
20,238881,5714489,-392,0,NaN,NaN,0.000,0,252000.000,23679.000,...,0,0,0,0,0,0,0,0,0,0
21,222183,5714491,-784,0,1008.0,NaN,0.000,0,0.000,-411.615,...,0,0,0,0,0,0,0,0,0,0
22,222183,5714492,-774,0,625.0,NaN,NaN,0,127840.500,0.000,...,0,0,0,0,0,0,0,0,0,0
23,222183,5714493,-395,0,1431.0,NaN,NaN,0,1350000.000,1185493.500,...,0,0,0,0,0,0,0,0,0,0
24,222183,5714495,-2744,0,-2561.0,-2559.0,310.500,0,18157.500,NaN,...,0,0,0,0,0,0,0,0,0,0
25,222183,5714496,-1103,0,-7.0,-343.0,20493.270,0,675000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
26,222183,5714497,-315,0,1512.0,NaN,88821.000,0,3709552.500,NaN,...,0,0,0,0,0,0,0,0,0,0
27,426155,5714498,-1331,0,-994.0,-1023.0,1350.000,0,39433.500,0.000,...,0,0,0,0,0,0,0,0,0,0
28,426155,5714499,-2534,0,-2352.0,-2347.0,NaN,0,38830.500,0.000,...,0,0,0,0,0,0,0,0,0,0
29,426155,5714500,-845,0,-480.0,-480.0,0.000,0,67500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716398,312021,5057541,-1529,0,-829.0,-829.0,NaN,0,209898.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716399,232638,5057553,-613,0,721.0,NaN,NaN,0,972000.000,886297.500,...,0,0,0,0,0,0,0,0,0,0
1716400,318662,5057561,-815,0,1011.0,NaN,NaN,0,147150.000,105358.500,...,0,0,0,0,0,0,0,0,0,0
1716401,145715,5057569,-2333,0,-2027.0,-1984.0,173.070,0,35032.500,0.000,...,0,0,0,0,0,0,0,0,0,0
1716402,352358,5057580,-1714,0,-1530.0,-1564.0,NaN,0,35271.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716403,361928,5057589,-765,0,1061.0,NaN,NaN,0,1431000.000,1092226.500,...,0,0,0,0,0,0,0,0,0,0
1716404,166279,5057599,-99,0,997.0,NaN,0.000,0,450000.000,432787.500,...,0,0,0,0,0,0,0,0,0,0
1716405,438109,5057605,-2390,0,-2053.0,-2082.0,11317.590,0,112204.350,0.000,...,0,0,0,0,0,0,0,0,0,0
1716406,335468,5057618,-2517,0,-660.0,-2363.0,0.000,0,473940.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716407,146896,5057629,-1990,0,-1244.0,-1248.0,NaN,0,90000.000,NaN,...,0,0,0,0,0,0,0,0,0,0
1716408,146896,5057632,-434,0,-344.0,-344.0,NaN,0,234000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716409,146896,5057636,-1705,0,-582.0,-582.0,0.000,0,0.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716410,280228,5057642,-575,0,813.0,NaN,NaN,0,67500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716411,232118,5057652,-821,0,-425.0,-545.0,0.000,0,108765.720,0.000,...,0,0,0,0,0,0,0,0,0,0
1716412,288038,5057657,-541,0,7.0,NaN,NaN,0,225000.000,10971.000,...,0,0,0,0,0,0,0,0,0,0
1716413,288038,5057665,-463,0,-36.0,-36.0,6863.715,0,110878.470,0.000,...,0,0,0,0,0,0,0,0,0,0
1716414,445222,5057676,-1628,0,-1320.0,-1320.0,5693.625,0,57834.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716415,317217,5057684,-1970,0,-1577.0,-1577.0,NaN,0,93955.500,NaN,...,0,0,0,0,0,0,0,0,0,0
1716416,433007,5057695,-1100,0,-732.0,-731.0,NaN,0,98775.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716417,433007,5057703,-740,0,31128.0,NaN,NaN,0,67500.000,2466.000,...,0,0,0,0,0,0,0,0,0,0
1716418,433007,5057708,-1389,0,-1299.0,-1299.0,0.000,0,334158.435,0.000,...,0,0,0,0,0,0,0,0,0,0
1716419,352790,5057718,-1808,0,-1596.0,-1625.0,8100.000,0,28248.840,0.000,...,0,0,0,0,0,0,0,0,0,0
1716420,352790,5057725,-99,0,-83.0,-98.0,NaN,0,27000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716421,375755,5057734,-1335,0,-1152.0,-1152.0,NaN,0,195408.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716422,375755,5057742,-2648,0,31129.0,-189.0,NaN,0,202500.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716423,259355,5057750,-44,0,-30.0,NaN,0.000,0,11250.000,11250.000,...,0,0,0,0,1,0,0,0,0,0
1716424,100044,5057754,-2648,0,-2433.0,-2493.0,5476.500,0,38130.840,0.000,...,0,0,0,0,0,0,0,0,0,0
1716425,100044,5057762,-1809,0,-1628.0,-970.0,NaN,0,15570.000,NaN,...,0,0,0,0,0,0,0,0,0,0
1716426,246829,5057770,-1878,0,-1513.0,-1513.0,NaN,0,36000.000,0.000,...,0,0,0,0,0,0,0,0,0,0
1716427,246829,5057778,-463,0,NaN,-387.0,NaN,0,22500.000,0.000,...,0,0,0,0,1,0,0,0,0,0

In [11]:
bb_aggregations = {'MONTHS_BALANCE': ['min', 'max', 'size']}

In [12]:
bb_aggregations

{'MONTHS_BALANCE': ['min', 'max', 'size']}

In [13]:
for col in bb_cat:
        bb_aggregations[col] = ['mean']

In [14]:
bb_aggregations

{'MONTHS_BALANCE': ['min', 'max', 'size'],
 'STATUS_0': ['mean'],
 'STATUS_1': ['mean'],
 'STATUS_2': ['mean'],
 'STATUS_3': ['mean'],
 'STATUS_4': ['mean'],
 'STATUS_5': ['mean'],
 'STATUS_C': ['mean'],
 'STATUS_X': ['mean'],
 'STATUS_nan': ['mean']}

In [15]:
bb_agg = bb.groupby('SK_ID_BUREAU').agg(bb_aggregations)

In [16]:
bb_agg

             MONTHS_BALANCE           STATUS_0  STATUS_1 STATUS_2 STATUS_3  \
                        min max size      mean      mean     mean     mean
SK_ID_BUREAU
5001709                 -96   0   97  0.000000  0.000000      0.0      0.0
5001710                 -82   0   83  0.060241  0.000000      0.0      0.0
5001711                  -3   0    4  0.750000  0.000000      0.0      0.0
5001712                 -18   0   19  0.526316  0.000000      0.0      0.0
5001713                 -21   0   22  0.000000  0.000000      0.0      0.0
5001714                 -14   0   15  0.000000  0.000000      0.0      0.0
5001715                 -59   0   60  0.000000  0.000000      0.0      0.0
5001716                 -85   0   86  0.313953  0.000000      0.0      0.0
5001717                 -21   0   22  0.772727  0.000000      0.0      0.0
5001718                 -38   0   39  0.615385  0.051282      0.0      0.0
5001719                 -42   0   43  0.046512  0.000000      0.0      0.0
5001720                 -35   0   36  0.805556  0.194444      0.0      0.0
5001721                 -84   0   85  0.152941  0.000000      0.0      0.0
5001722                 -85   0   86  0.313953  0.232558      0.0      0.0
5001723                 -30   0   31  0.258065  0.000000      0.0      0.0
5001724                 -30   0   31  0.000000  0.000000      0.0      0.0
5001725                  -7   0    8  0.875000  0.000000      0.0      0.0
5001726                 -38   0   39  0.153846  0.000000      0.0      0.0
5001727                 -94   0   95  0.242105  0.000000      0.0      0.0
5001728                   0   0    1  1.000000  0.000000      0.0      0.0
5001729                  -6   0    7  0.857143  0.000000      0.0      0.0
5001730                 -60   0   61  0.081967  0.000000      0.0      0.0
5001731                 -10   0   11  0.000000  0.000000      0.0      0.0
5001732                 -35   0   36  0.000000  0.000000      0.0      0.0
5001733                 -10   0   11  0.000000  0.000000      0.0      0.0
5001734                  -2   0    3  1.000000  0.000000      0.0      0.0
5001735                 -23   0   24  0.041667  0.000000      0.0      0.0
5001736                 -23   0   24  0.166667  0.000000      0.0      0.0
5001737                 -21   0   22  0.545455  0.000000      0.0      0.0
5001738                 -43   0   44  0.272727  0.000000      0.0      0.0
...                     ...  ..  ...       ...       ...      ...      ...
6842859                 -35   0   36  0.166667  0.000000      0.0      0.0
6842860                 -35   0   36  0.805556  0.000000      0.0      0.0
6842861                 -35   0   36  0.638889  0.000000      0.0      0.0
6842862                 -68   0   69  0.246377  0.000000      0.0      0.0
6842863                 -78   0   79  0.012658  0.000000      0.0      0.0
6842864                 -34   0   35  0.457143  0.000000      0.0      0.0
6842865                 -18   0   19  1.000000  0.000000      0.0      0.0
6842866                  -4   0    5  1.000000  0.000000      0.0      0.0
6842867                 -14   0   15  1.000000  0.000000      0.0      0.0
6842868                 -55   0   56  0.071429  0.000000      0.0      0.0
6842869                 -26   0   27  0.074074  0.000000      0.0      0.0
6842870                 -35   0   36  0.111111  0.000000      0.0      0.0
6842871                 -18   0   19  0.631579  0.000000      0.0      0.0
6842872                 -87   0   88  0.079545  0.000000      0.0      0.0
6842873                 -55   0   56  0.071429  0.000000      0.0      0.0
6842874                 -89   0   90  0.088889  0.011111      0.0      0.0
6842875                 -76   0   77  0.311688  0.000000      0.0      0.0
6842876                 -25   0   26  0.038462  0.000000      0.0      0.0
6842877                 -40   0   41  0.975610  0.000000      0.0      0.0
6842878                 -29   0   30  0.166667  0.000000      0.0      0.0
6842879                 -38   0   39  0.153846  0.000000      0.0      0.0
6842880                 -57   0   58  0.120690  0.034483      0.0      0.0
6842881                 -31   0   32  0.625000  0.000000      0.0      0.0
6842882                  -7   0    8  0.500000  0.000000      0.0      0.0
6842883                 -36   0   37  0.027027  0.000000      0.0      0.0
6842884                 -47   0   48  0.187500  0.000000      0.0      0.0
6842885                 -23   0   24  0.500000  0.000000      0.0      0.0
6842886                 -32   0   33  0.242424  0.000000      0.0      0.0
6842887                 -36   0   37  0.162162  0.000000      0.0      0.0
6842888                 -61   0   62  0.145161  0.016129      0.0      0.0

             STATUS_4 STATUS_5  STATUS_C  STATUS_X STATUS_nan
                 mean     mean      mean      mean       mean
SK_ID_BUREAU
5001709           0.0      0.0  0.886598  0.113402          0
5001710           0.0      0.0  0.578313  0.361446          0
5001711           0.0      0.0  0.000000  0.250000          0
5001712           0.0      0.0  0.473684  0.000000          0
5001713           0.0      0.0  0.000000  1.000000          0
5001714           0.0      0.0  0.000000  1.000000          0
5001715           0.0      0.0  0.000000  1.000000          0
5001716           0.0      0.0  0.453488  0.232558          0
5001717           0.0      0.0  0.227273  0.000000          0
5001718           0.0      0.0  0.076923  0.256410          0
5001719           0.0      0.0  0.953488  0.000000          0
5001720           0.0      0.0  0.000000  0.000000          0
5001721           0.0      0.0  0.847059  0.000000          0
5001722           0.0      0.0  0.453488  0.000000          0
5001723           0.0      0.0  0.000000  0.741935          0
5001724           0.0      0.0  0.709677  0.290323          0
5001725           0.0      0.0  0.000000  0.125000          0
5001726           0.0      0.0  0.846154  0.000000          0
5001727           0.0      0.0  0.757895  0.000000          0
5001728           0.0      0.0  0.000000  0.000000          0
5001729           0.0      0.0  0.142857  0.000000          0
5001730           0.0      0.0  0.918033  0.000000          0
5001731           0.0      0.0  0.000000  1.000000          0
5001732           0.0      0.0  0.000000  1.000000          0
5001733           0.0      0.0  0.000000  1.000000          0
5001734           0.0      0.0  0.000000  0.000000          0
5001735           0.0      0.0  0.958333  0.000000          0
5001736           0.0      0.0  0.833333  0.000000          0
5001737           0.0      0.0  0.454545  0.000000          0
5001738           0.0      0.0  0.727273  0.000000          0
...               ...      ...       ...       ...        ...
6842859           0.0      0.0  0.833333  0.000000          0
6842860           0.0      0.0  0.000000  0.194444          0
6842861           0.0      0.0  0.055556  0.305556          0
6842862           0.0      0.0  0.217391  0.536232          0
6842863           0.0      0.0  0.556962  0.430380          0
6842864           0.0      0.0  0.000000  0.542857          0
6842865           0.0      0.0  0.000000  0.000000          0
6842866           0.0      0.0  0.000000  0.000000          0
6842867           0.0      0.0  0.000000  0.000000          0
6842868           0.0      0.0  0.928571  0.000000          0
6842869           0.0      0.0  0.925926  0.000000          0
6842870           0.0      0.0  0.833333  0.055556          0
6842871           0.0      0.0  0.000000  0.368421          0
6842872           0.0      0.0  0.886364  0.034091          0
6842873           0.0      0.0  0.928571  0.000000          0
6842874           0.0      0.0  0.888889  0.011111          0
6842875           0.0      0.0  0.675325  0.012987          0
6842876           0.0      0.0  0.000000  0.961538          0
6842877           0.0      0.0  0.000000  0.024390          0
6842878           0.0      0.0  0.766667  0.066667          0
6842879           0.0      0.0  0.512821  0.333333          0
6842880           0.0      0.0  0.620690  0.224138          0
6842881           0.0      0.0  0.000000  0.375000          0
6842882           0.0      0.0  0.000000  0.500000          0
6842883           0.0      0.0  0.945946  0.027027          0
6842884           0.0      0.0  0.416667  0.395833          0
6842885           0.0      0.5  0.000000  0.000000          0
6842886           0.0      0.0  0.757576  0.000000          0
6842887           0.0      0.0  0.837838  0.000000          0
6842888           0.0      0.0  0.838710  0.000000          0

[817395 rows x 12 columns]

In [17]:
bb_agg.columns = pd.Index([e[0] + "_" + e[1].upper() for e in bb_agg.columns.tolist()])

In [18]:
bb_agg.columns

Index(['MONTHS_BALANCE_MIN', 'MONTHS_BALANCE_MAX', 'MONTHS_BALANCE_SIZE',
       'STATUS_0_MEAN', 'STATUS_1_MEAN', 'STATUS_2_MEAN', 'STATUS_3_MEAN',
       'STATUS_4_MEAN', 'STATUS_5_MEAN', 'STATUS_C_MEAN', 'STATUS_X_MEAN',
       'STATUS_nan_MEAN'],
      dtype='object')

In [19]:
bureau = bureau.join(bb_agg, how='left', on='SK_ID_BUREAU')

In [20]:
list(bureau)

['SK_ID_CURR',
 'SK_ID_BUREAU',
 'DAYS_CREDIT',
 'CREDIT_DAY_OVERDUE',
 'DAYS_CREDIT_ENDDATE',
 'DAYS_ENDDATE_FACT',
 'AMT_CREDIT_MAX_OVERDUE',
 'CNT_CREDIT_PROLONG',
 'AMT_CREDIT_SUM',
 'AMT_CREDIT_SUM_DEBT',
 'AMT_CREDIT_SUM_LIMIT',
 'AMT_CREDIT_SUM_OVERDUE',
 'DAYS_CREDIT_UPDATE',
 'AMT_ANNUITY',
 'CREDIT_ACTIVE_Active',
 'CREDIT_ACTIVE_Bad debt',
 'CREDIT_ACTIVE_Closed',
 'CREDIT_ACTIVE_Sold',
 'CREDIT_ACTIVE_nan',
 'CREDIT_CURRENCY_currency 1',
 'CREDIT_CURRENCY_currency 2',
 'CREDIT_CURRENCY_currency 3',
 'CREDIT_CURRENCY_currency 4',
 'CREDIT_CURRENCY_nan',
 'CREDIT_TYPE_Another type of loan',
 'CREDIT_TYPE_Car loan',
 'CREDIT_TYPE_Cash loan (non-earmarked)',
 'CREDIT_TYPE_Consumer credit',
 'CREDIT_TYPE_Credit card',
 'CREDIT_TYPE_Interbank credit',
 'CREDIT_TYPE_Loan for business development',
 'CREDIT_TYPE_Loan for purchase of shares (margin lending)',
 'CREDIT_TYPE_Loan for the purchase of equipment',
 'CREDIT_TYPE_Loan for working capital replenishment',
 'CREDIT_TYPE_Microloan',
 'CREDIT_TYPE_Mobile operator loan',
 'CREDIT_TYPE_Mortgage',
 'CREDIT_TYPE_Real estate loan',
 'CREDIT_TYPE_Unknown type of loan',
 'CREDIT_TYPE_nan',
 'MONTHS_BALANCE_MIN',
 'MONTHS_BALANCE_MAX',
 'MONTHS_BALANCE_SIZE',
 'STATUS_0_MEAN',
 'STATUS_1_MEAN',
 'STATUS_2_MEAN',
 'STATUS_3_MEAN',
 'STATUS_4_MEAN',
 'STATUS_5_MEAN',
 'STATUS_C_MEAN',
 'STATUS_X_MEAN',
 'STATUS_nan_MEAN']

In [21]:
len(list(bureau))

52

In [22]:
bureau.drop(['SK_ID_BUREAU'], axis=1, inplace= True)

In [23]:
bureau.head(10)

,SK_ID_CURR,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,...,MONTHS_BALANCE_SIZE,STATUS_0_MEAN,STATUS_1_MEAN,STATUS_2_MEAN,STATUS_3_MEAN,STATUS_4_MEAN,STATUS_5_MEAN,STATUS_C_MEAN,STATUS_X_MEAN,STATUS_nan_MEAN
0,215354,-497,0,-153.0,-153.0,NaN,0,91323.00,0.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,215354,-208,0,1075.0,NaN,NaN,0,225000.00,171342.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,215354,-203,0,528.0,NaN,NaN,0,464323.50,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,215354,-203,0,NaN,NaN,NaN,0,90000.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,215354,-629,0,1197.0,NaN,77674.5,0,2700000.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,215354,-273,0,27460.0,NaN,0.0,0,180000.00,71017.38,108982.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,215354,-43,0,79.0,NaN,0.0,0,42103.80,42103.80,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,162297,-1896,0,-1684.0,-1710.0,14985.0,0,76878.45,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,162297,-1146,0,-811.0,-840.0,0.0,0,103007.70,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,162297,-1146,0,-484.0,NaN,0.0,0,4500.00,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
 del bb, bb_agg

In [25]:
gc.collect()

41

 ## Bureau and bureau_balance numeric features

In [26]:
 num_aggregations = {
        'DAYS_CREDIT': ['min', 'max', 'mean', 'var'],
        'DAYS_CREDIT_ENDDATE': ['min', 'max', 'mean'],
        'DAYS_CREDIT_UPDATE': ['mean'],
        'CREDIT_DAY_OVERDUE': ['max', 'mean'],
        'AMT_CREDIT_MAX_OVERDUE': ['mean'],
        'AMT_CREDIT_SUM': ['max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_DEBT': ['max', 'mean', 'sum'],
        'AMT_CREDIT_SUM_OVERDUE': ['mean'],
        'AMT_CREDIT_SUM_LIMIT': ['mean', 'sum'],
        'AMT_ANNUITY': ['max', 'mean'],
        'CNT_CREDIT_PROLONG': ['sum'],
        'MONTHS_BALANCE_MIN': ['min'],
        'MONTHS_BALANCE_MAX': ['max'],
        'MONTHS_BALANCE_SIZE': ['mean', 'sum']
    }

### Bureau and bureau_balance categorical features

In [28]:

cat_aggregations = {}
for cat in bureau_cat: cat_aggregations[cat] = ['mean']

In [29]:
cat_aggregations

{'CREDIT_ACTIVE_Active': ['mean'],
 'CREDIT_ACTIVE_Bad debt': ['mean'],
 'CREDIT_ACTIVE_Closed': ['mean'],
 'CREDIT_ACTIVE_Sold': ['mean'],
 'CREDIT_ACTIVE_nan': ['mean'],
 'CREDIT_CURRENCY_currency 1': ['mean'],
 'CREDIT_CURRENCY_currency 2': ['mean'],
 'CREDIT_CURRENCY_currency 3': ['mean'],
 'CREDIT_CURRENCY_currency 4': ['mean'],
 'CREDIT_CURRENCY_nan': ['mean'],
 'CREDIT_TYPE_Another type of loan': ['mean'],
 'CREDIT_TYPE_Car loan': ['mean'],
 'CREDIT_TYPE_Cash loan (non-earmarked)': ['mean'],
 'CREDIT_TYPE_Consumer credit': ['mean'],
 'CREDIT_TYPE_Credit card': ['mean'],
 'CREDIT_TYPE_Interbank credit': ['mean'],
 'CREDIT_TYPE_Loan for business development': ['mean'],
 'CREDIT_TYPE_Loan for purchase of shares (margin lending)': ['mean'],
 'CREDIT_TYPE_Loan for the purchase of equipment': ['mean'],
 'CREDIT_TYPE_Loan for working capital replenishment': ['mean'],
 'CREDIT_TYPE_Microloan': ['mean'],
 'CREDIT_TYPE_Mobile operator loan': ['mean'],
 'CREDIT_TYPE_Mortgage': ['mean'],
 'CREDIT_TYPE_Real estate loan': ['mean'],
 'CREDIT_TYPE_Unknown type of loan': ['mean'],
 'CREDIT_TYPE_nan': ['mean']}

In [30]:
len(cat_aggregations)

26

In [31]:
for cat in bb_cat: cat_aggregations[cat + "_MEAN"] = ['mean']

In [32]:
cat_aggregations

{'CREDIT_ACTIVE_Active': ['mean'],
 'CREDIT_ACTIVE_Bad debt': ['mean'],
 'CREDIT_ACTIVE_Closed': ['mean'],
 'CREDIT_ACTIVE_Sold': ['mean'],
 'CREDIT_ACTIVE_nan': ['mean'],
 'CREDIT_CURRENCY_currency 1': ['mean'],
 'CREDIT_CURRENCY_currency 2': ['mean'],
 'CREDIT_CURRENCY_currency 3': ['mean'],
 'CREDIT_CURRENCY_currency 4': ['mean'],
 'CREDIT_CURRENCY_nan': ['mean'],
 'CREDIT_TYPE_Another type of loan': ['mean'],
 'CREDIT_TYPE_Car loan': ['mean'],
 'CREDIT_TYPE_Cash loan (non-earmarked)': ['mean'],
 'CREDIT_TYPE_Consumer credit': ['mean'],
 'CREDIT_TYPE_Credit card': ['mean'],
 'CREDIT_TYPE_Interbank credit': ['mean'],
 'CREDIT_TYPE_Loan for business development': ['mean'],
 'CREDIT_TYPE_Loan for purchase of shares (margin lending)': ['mean'],
 'CREDIT_TYPE_Loan for the purchase of equipment': ['mean'],
 'CREDIT_TYPE_Loan for working capital replenishment': ['mean'],
 'CREDIT_TYPE_Microloan': ['mean'],
 'CREDIT_TYPE_Mobile operator loan': ['mean'],
 'CREDIT_TYPE_Mortgage': ['mean'],
 'CREDIT_TYPE_Real estate loan': ['mean'],
 'CREDIT_TYPE_Unknown type of loan': ['mean'],
 'CREDIT_TYPE_nan': ['mean'],
 'STATUS_0_MEAN': ['mean'],
 'STATUS_1_MEAN': ['mean'],
 'STATUS_2_MEAN': ['mean'],
 'STATUS_3_MEAN': ['mean'],
 'STATUS_4_MEAN': ['mean'],
 'STATUS_5_MEAN': ['mean'],
 'STATUS_C_MEAN': ['mean'],
 'STATUS_X_MEAN': ['mean'],
 'STATUS_nan_MEAN': ['mean']}

In [33]:
len(cat_aggregations)

35

In [34]:
bureau_agg = bureau.groupby('SK_ID_CURR').agg({**num_aggregations, **cat_aggregations})

In [35]:
bureau_agg.head(5)

           DAYS_CREDIT                                  DAYS_CREDIT_ENDDATE  \
                   min  max         mean            var                 min
SK_ID_CURR
100001           -1572  -49  -735.000000  240043.666667             -1329.0
100002           -1437 -103  -874.000000  186150.000000             -1072.0
100003           -2586 -606 -1400.750000  827783.583333             -2434.0
100004           -1326 -408  -867.000000  421362.000000              -595.0
100005            -373  -62  -190.666667   26340.333333              -128.0

                               DAYS_CREDIT_UPDATE CREDIT_DAY_OVERDUE       \
               max        mean               mean                max mean
SK_ID_CURR
100001      1778.0   82.428571         -93.142857                  0  0.0
100002       780.0 -349.000000        -499.875000                  0  0.0
100003      1216.0 -544.500000        -816.000000                  0  0.0
100004      -382.0 -488.500000        -532.000000                  0  0.0
100005      1324.0  439.333333         -54.333333                  0  0.0

                 ...       CREDIT_TYPE_nan STATUS_0_MEAN STATUS_1_MEAN  \
                 ...                  mean          mean          mean
SK_ID_CURR       ...
100001           ...                     0      0.336651      0.007519
100002           ...                     0      0.406960      0.255682
100003           ...                     0           NaN           NaN
100004           ...                     0           NaN           NaN
100005           ...                     0      0.735043      0.000000

           STATUS_2_MEAN STATUS_3_MEAN STATUS_4_MEAN STATUS_5_MEAN  \
                    mean          mean          mean          mean
SK_ID_CURR
100001               0.0           0.0           0.0           0.0
100002               0.0           0.0           0.0           0.0
100003               NaN           NaN           NaN           NaN
100004               NaN           NaN           NaN           NaN
100005               0.0           0.0           0.0           0.0

           STATUS_C_MEAN STATUS_X_MEAN STATUS_nan_MEAN
                    mean          mean            mean
SK_ID_CURR
100001          0.441240      0.214590             0.0
100002          0.175426      0.161932             0.0
100003               NaN           NaN             NaN
100004               NaN           NaN             NaN
100005          0.128205      0.136752             0.0

[5 rows x 62 columns]

In [36]:
bureau_agg.columns = pd.Index(['BURO_' + e[0] + "_" + e[1].upper() for e in bureau_agg.columns.tolist()])

In [37]:
bureau_agg.columns

Index(['BURO_DAYS_CREDIT_MIN', 'BURO_DAYS_CREDIT_MAX', 'BURO_DAYS_CREDIT_MEAN',
       'BURO_DAYS_CREDIT_VAR', 'BURO_DAYS_CREDIT_ENDDATE_MIN',
       'BURO_DAYS_CREDIT_ENDDATE_MAX', 'BURO_DAYS_CREDIT_ENDDATE_MEAN',
       'BURO_DAYS_CREDIT_UPDATE_MEAN', 'BURO_CREDIT_DAY_OVERDUE_MAX',
       'BURO_CREDIT_DAY_OVERDUE_MEAN', 'BURO_AMT_CREDIT_MAX_OVERDUE_MEAN',
       'BURO_AMT_CREDIT_SUM_MAX', 'BURO_AMT_CREDIT_SUM_MEAN',
       'BURO_AMT_CREDIT_SUM_SUM', 'BURO_AMT_CREDIT_SUM_DEBT_MAX',
       'BURO_AMT_CREDIT_SUM_DEBT_MEAN', 'BURO_AMT_CREDIT_SUM_DEBT_SUM',
       'BURO_AMT_CREDIT_SUM_OVERDUE_MEAN', 'BURO_AMT_CREDIT_SUM_LIMIT_MEAN',
       'BURO_AMT_CREDIT_SUM_LIMIT_SUM', 'BURO_AMT_ANNUITY_MAX',
       'BURO_AMT_ANNUITY_MEAN', 'BURO_CNT_CREDIT_PROLONG_SUM',
       'BURO_MONTHS_BALANCE_MIN_MIN', 'BURO_MONTHS_BALANCE_MAX_MAX',
       'BURO_MONTHS_BALANCE_SIZE_MEAN', 'BURO_MONTHS_BALANCE_SIZE_SUM',
       'BURO_CREDIT_ACTIVE_Active_MEAN', 'BURO_CREDIT_ACTIVE_Bad debt_MEAN',
       'BURO_CREDIT_ACTIVE_Closed_MEAN', 'BURO_CREDIT_ACTIVE_Sold_MEAN',
       'BURO_CREDIT_ACTIVE_nan_MEAN', 'BURO_CREDIT_CURRENCY_currency 1_MEAN',
       'BURO_CREDIT_CURRENCY_currency 2_MEAN',
       'BURO_CREDIT_CURRENCY_currency 3_MEAN',
       'BURO_CREDIT_CURRENCY_currency 4_MEAN', 'BURO_CREDIT_CURRENCY_nan_MEAN',
       'BURO_CREDIT_TYPE_Another type of loan_MEAN',
       'BURO_CREDIT_TYPE_Car loan_MEAN',
       'BURO_CREDIT_TYPE_Cash loan (non-earmarked)_MEAN',
       'BURO_CREDIT_TYPE_Consumer credit_MEAN',
       'BURO_CREDIT_TYPE_Credit card_MEAN',
       'BURO_CREDIT_TYPE_Interbank credit_MEAN',
       'BURO_CREDIT_TYPE_Loan for business development_MEAN',
       'BURO_CREDIT_TYPE_Loan for purchase of shares (margin lending)_MEAN',
       'BURO_CREDIT_TYPE_Loan for the purchase of equipment_MEAN',
       'BURO_CREDIT_TYPE_Loan for working capital replenishment_MEAN',
       'BURO_CREDIT_TYPE_Microloan_MEAN',
       'BURO_CREDIT_TYPE_Mobile operator loan_MEAN',
       'BURO_CREDIT_TYPE_Mortgage_MEAN',
       'BURO_CREDIT_TYPE_Real estate loan_MEAN',
       'BURO_CREDIT_TYPE_Unknown type of loan_MEAN',
       'BURO_CREDIT_TYPE_nan_MEAN', 'BURO_STATUS_0_MEAN_MEAN',
       'BURO_STATUS_1_MEAN_MEAN', 'BURO_STATUS_2_MEAN_MEAN',
       'BURO_STATUS_3_MEAN_MEAN', 'BURO_STATUS_4_MEAN_MEAN',
       'BURO_STATUS_5_MEAN_MEAN', 'BURO_STATUS_C_MEAN_MEAN',
       'BURO_STATUS_X_MEAN_MEAN', 'BURO_STATUS_nan_MEAN_MEAN'],
      dtype='object')

###  Bureau: Active credits - using only numerical aggregations

In [38]:
active = bureau[bureau['CREDIT_ACTIVE_Active'] == 1]

In [39]:
active_agg = active.groupby('SK_ID_CURR').agg(num_aggregations)

In [42]:
active_agg.head(10)

           DAYS_CREDIT                                   DAYS_CREDIT_ENDDATE  \
                   min   max         mean            var                 min
SK_ID_CURR
100001            -559   -49  -309.333333   65110.333333               411.0
100002           -1042  -103  -572.500000  440860.500000               780.0
100003            -606  -606  -606.000000            NaN              1216.0
100005            -137   -62   -99.500000    2812.500000               122.0
100008             -78   -78   -78.000000            NaN               471.0
100009           -1293  -239  -591.750000  225664.916667              -209.0
100010           -1138 -1138 -1138.000000            NaN               689.0
100014            -423  -376  -399.500000    1104.500000               704.0
100016            -262  -128  -168.250000    3946.916667               223.0
100019            -495  -495  -495.000000       0.000000               419.0

                                 DAYS_CREDIT_UPDATE CREDIT_DAY_OVERDUE       \
                max         mean               mean                max mean
SK_ID_CURR
100001       1778.0  1030.333333         -10.666667                  0  0.0
100002        780.0   780.000000         -15.500000                  0  0.0
100003       1216.0  1216.000000         -43.000000                  0  0.0
100005       1324.0   723.000000         -21.000000                  0  0.0
100008        471.0   471.000000         -16.000000                  0  0.0
100009       1402.0   596.500000        -245.750000                  0  0.0
100010        689.0   689.000000         -18.000000                  0  0.0
100014        723.0   713.500000         -29.500000                  0  0.0
100016        845.0   381.750000         -15.000000                  0  0.0
100019      10463.0  5441.000000         -26.500000                  0  0.0

            ...  AMT_CREDIT_SUM_OVERDUE AMT_CREDIT_SUM_LIMIT              \
            ...                    mean                 mean         sum
SK_ID_CURR  ...
100001      ...                     0.0               0.0000       0.000
100002      ...                     0.0           15994.2825   31988.565
100003      ...                     0.0          810000.0000  810000.000
100005      ...                     0.0               0.0000       0.000
100008      ...                     0.0               0.0000       0.000
100009      ...                     0.0               0.0000       0.000
100010      ...                     0.0               0.0000       0.000
100014      ...                     0.0               0.0000       0.000
100016      ...                     0.0               0.0000       0.000
100019      ...                     0.0          135000.0000  270000.000

           AMT_ANNUITY           CNT_CREDIT_PROLONG MONTHS_BALANCE_MIN  \
                   max      mean                sum                min
SK_ID_CURR
100001         10822.5   8272.50                  0              -18.0
100002             0.0      0.00                  0              -34.0
100003             NaN       NaN                  0                NaN
100005          4261.5   2130.75                  0               -4.0
100008             NaN       NaN                  0                NaN
100009             NaN       NaN                  0                NaN
100010             NaN       NaN                  0              -37.0
100014             NaN       NaN                  0                NaN
100016             NaN       NaN                  0                NaN
100019         27000.0  27000.00                  0              -16.0

           MONTHS_BALANCE_MAX MONTHS_BALANCE_SIZE
                          max                mean   sum
SK_ID_CURR
100001                    0.0           10.666667  32.0
100002                    0.0           10.000000  20.0
100003                    NaN                 NaN   0.0
100005                    0.0            4.000000   8.0
100008                    NaN                 NaN   0.0
100009                    NaN                 NaN   0.0
100010                   -2.0           36.000000  36.0
100014                    NaN                 NaN   0.0
100016                    NaN                 NaN   0.0
100019                    0.0           17.000000  34.0

[10 rows x 27 columns]

In [43]:
cols = active_agg.columns.tolist()
cols

In [48]:
active_agg.columns = pd.Index(['ACTIVE_' + e[0] + "_" + e[1].upper() for e in active_agg.columns.tolist()])
active_agg.columns

Index(['ACTIVE_DAYS_CREDIT_MIN', 'ACTIVE_DAYS_CREDIT_MAX',
       'ACTIVE_DAYS_CREDIT_MEAN', 'ACTIVE_DAYS_CREDIT_VAR',
       'ACTIVE_DAYS_CREDIT_ENDDATE_MIN', 'ACTIVE_DAYS_CREDIT_ENDDATE_MAX',
       'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN', 'ACTIVE_DAYS_CREDIT_UPDATE_MEAN',
       'ACTIVE_CREDIT_DAY_OVERDUE_MAX', 'ACTIVE_CREDIT_DAY_OVERDUE_MEAN',
       'ACTIVE_AMT_CREDIT_MAX_OVERDUE_MEAN', 'ACTIVE_AMT_CREDIT_SUM_MAX',
       'ACTIVE_AMT_CREDIT_SUM_MEAN', 'ACTIVE_AMT_CREDIT_SUM_SUM',
       'ACTIVE_AMT_CREDIT_SUM_DEBT_MAX', 'ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN',
       'ACTIVE_AMT_CREDIT_SUM_DEBT_SUM', 'ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN',
       'ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN', 'ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM',
       'ACTIVE_AMT_ANNUITY_MAX', 'ACTIVE_AMT_ANNUITY_MEAN',
       'ACTIVE_CNT_CREDIT_PROLONG_SUM', 'ACTIVE_MONTHS_BALANCE_MIN_MIN',
       'ACTIVE_MONTHS_BALANCE_MAX_MAX', 'ACTIVE_MONTHS_BALANCE_SIZE_MEAN',
       'ACTIVE_MONTHS_BALANCE_SIZE_SUM'],
      dtype='object')

In [49]:
active_agg.head(10)

,ACTIVE_DAYS_CREDIT_MIN,ACTIVE_DAYS_CREDIT_MAX,ACTIVE_DAYS_CREDIT_MEAN,ACTIVE_DAYS_CREDIT_VAR,ACTIVE_DAYS_CREDIT_ENDDATE_MIN,ACTIVE_DAYS_CREDIT_ENDDATE_MAX,ACTIVE_DAYS_CREDIT_ENDDATE_MEAN,ACTIVE_DAYS_CREDIT_UPDATE_MEAN,ACTIVE_CREDIT_DAY_OVERDUE_MAX,ACTIVE_CREDIT_DAY_OVERDUE_MEAN,...,ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM,ACTIVE_AMT_ANNUITY_MAX,ACTIVE_AMT_ANNUITY_MEAN,ACTIVE_CNT_CREDIT_PROLONG_SUM,ACTIVE_MONTHS_BALANCE_MIN_MIN,ACTIVE_MONTHS_BALANCE_MAX_MAX,ACTIVE_MONTHS_BALANCE_SIZE_MEAN,ACTIVE_MONTHS_BALANCE_SIZE_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,-559,-49,-309.333333,65110.333333,411.0,1778.0,1030.333333,-10.666667,0,0.0,...,0.0,0.0000,0.000,10822.5,8272.50,0,-18.0,0.0,10.666667,32.0
100002,-1042,-103,-572.500000,440860.500000,780.0,780.0,780.000000,-15.500000,0,0.0,...,0.0,15994.2825,31988.565,0.0,0.00,0,-34.0,0.0,10.000000,20.0
100003,-606,-606,-606.000000,NaN,1216.0,1216.0,1216.000000,-43.000000,0,0.0,...,0.0,810000.0000,810000.000,NaN,NaN,0,NaN,NaN,NaN,0.0
100005,-137,-62,-99.500000,2812.500000,122.0,1324.0,723.000000,-21.000000,0,0.0,...,0.0,0.0000,0.000,4261.5,2130.75,0,-4.0,0.0,4.000000,8.0
100008,-78,-78,-78.000000,NaN,471.0,471.0,471.000000,-16.000000,0,0.0,...,0.0,0.0000,0.000,NaN,NaN,0,NaN,NaN,NaN,0.0
100009,-1293,-239,-591.750000,225664.916667,-209.0,1402.0,596.500000,-245.750000,0,0.0,...,0.0,0.0000,0.000,NaN,NaN,0,NaN,NaN,NaN,0.0
100010,-1138,-1138,-1138.000000,NaN,689.0,689.0,689.000000,-18.000000,0,0.0,...,0.0,0.0000,0.000,NaN,NaN,0,-37.0,-2.0,36.000000,36.0
100014,-423,-376,-399.500000,1104.500000,704.0,723.0,713.500000,-29.500000,0,0.0,...,0.0,0.0000,0.000,NaN,NaN,0,NaN,NaN,NaN,0.0
100016,-262,-128,-168.250000,3946.916667,223.0,845.0,381.750000,-15.000000,0,0.0,...,0.0,0.0000,0.000,NaN,NaN,0,NaN,NaN,NaN,0.0
100019,-495,-495,-495.000000,0.000000,419.0,10463.0,5441.000000,-26.500000,0,0.0,...,0.0,135000.0000,270000.000,27000.0,27000.00,0,-16.0,0.0,17.000000,34.0

In [50]:
bureau_agg = bureau_agg.join(active_agg, how='left', on='SK_ID_CURR')

In [51]:
bureau_agg

,BURO_DAYS_CREDIT_MIN,BURO_DAYS_CREDIT_MAX,BURO_DAYS_CREDIT_MEAN,BURO_DAYS_CREDIT_VAR,BURO_DAYS_CREDIT_ENDDATE_MIN,BURO_DAYS_CREDIT_ENDDATE_MAX,BURO_DAYS_CREDIT_ENDDATE_MEAN,BURO_DAYS_CREDIT_UPDATE_MEAN,BURO_CREDIT_DAY_OVERDUE_MAX,BURO_CREDIT_DAY_OVERDUE_MEAN,...,ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN,ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM,ACTIVE_AMT_ANNUITY_MAX,ACTIVE_AMT_ANNUITY_MEAN,ACTIVE_CNT_CREDIT_PROLONG_SUM,ACTIVE_MONTHS_BALANCE_MIN_MIN,ACTIVE_MONTHS_BALANCE_MAX_MAX,ACTIVE_MONTHS_BALANCE_SIZE_MEAN,ACTIVE_MONTHS_BALANCE_SIZE_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,-1572,-49,-735.000000,2.400437e+05,-1329.0,1778.0,82.428571,-93.142857,0,0.0,...,0.000,0.0000,0.000,10822.500,8272.5000,0.0,-18.0,0.0,10.666667,32.0
100002,-1437,-103,-874.000000,1.861500e+05,-1072.0,780.0,-349.000000,-499.875000,0,0.0,...,0.000,15994.2825,31988.565,0.000,0.0000,0.0,-34.0,0.0,10.000000,20.0
100003,-2586,-606,-1400.750000,8.277836e+05,-2434.0,1216.0,-544.500000,-816.000000,0,0.0,...,0.000,810000.0000,810000.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100004,-1326,-408,-867.000000,4.213620e+05,-595.0,-382.0,-488.500000,-532.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100005,-373,-62,-190.666667,2.634033e+04,-128.0,1324.0,439.333333,-54.333333,0,0.0,...,0.000,0.0000,0.000,4261.500,2130.7500,0.0,-4.0,0.0,4.000000,8.0
100007,-1149,-1149,-1149.000000,NaN,-783.0,-783.0,-783.000000,-783.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100008,-1097,-78,-757.333333,3.461203e+05,-853.0,471.0,-391.333333,-611.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100009,-2882,-239,-1271.500000,4.426300e+05,-2152.0,1402.0,-794.937500,-851.611111,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100010,-2741,-1138,-1939.500000,1.284804e+06,-928.0,689.0,-119.500000,-578.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,-37.0,-2.0,36.000000,36.0
100011,-2508,-1309,-1773.000000,3.334180e+05,-2173.0,-860.0,-1293.250000,-1454.750000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100013,-2070,-1210,-1737.500000,1.552083e+05,-1707.0,-567.0,-1068.000000,-775.500000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100014,-2308,-376,-1095.375000,5.095088e+05,-2004.0,723.0,-387.375000,-615.875000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100015,-1409,-319,-947.750000,2.073689e+05,-1045.0,-16.0,-598.250000,-551.250000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100016,-1634,-128,-618.428571,4.381120e+05,-1369.0,845.0,-217.142857,-405.857143,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100017,-2881,-909,-1944.333333,5.387127e+05,-2546.0,197.0,-1512.333333,-1594.333333,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100019,-495,-495,-495.000000,0.000000e+00,419.0,10463.0,5441.000000,-26.500000,0,0.0,...,0.000,135000.0000,270000.000,27000.000,27000.0000,0.0,-16.0,0.0,17.000000,34.0
100020,-492,-90,-261.500000,3.018500e+04,-311.0,277.0,-32.500000,-130.750000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100022,-385,-289,-337.000000,4.608000e+03,441.0,1439.0,940.000000,-28.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100023,-2624,-157,-1164.384615,4.625959e+05,-2228.0,1669.0,-364.916667,-634.076923,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100025,-700,-700,-700.000000,NaN,1124.0,1124.0,1124.000000,-49.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100026,-1644,-148,-679.000000,7.007710e+05,217.0,1581.0,899.000000,-314.666667,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100027,-1983,-143,-793.000000,1.065100e+06,-1649.0,944.0,-278.333333,-600.666667,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100028,-2105,-269,-1401.750000,4.303558e+05,-1862.0,30885.0,2387.700000,-651.500000,0,0.0,...,0.000,25347.6900,101390.760,12897.090,7028.0250,0.0,-59.0,0.0,35.000000,175.0
100029,-2806,-110,-1416.750000,1.213672e+06,-1286.0,1563.0,-336.333333,-1041.750000,0,0.0,...,0.000,NaN,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100030,-1547,-418,-930.833333,1.994614e+05,-1173.0,1409.0,-61.600000,-411.166667,0,0.0,...,0.000,12828.0150,25656.030,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100031,-1365,-75,-579.571429,2.292140e+05,-269.0,1021.0,468.600000,-266.285714,0,0.0,...,0.000,NaN,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100032,-1389,-556,-1071.000000,1.604127e+05,-662.0,-191.0,-525.250000,-436.750000,0,0.0,...,0.000,0.0000,0.000,17437.500,17437.5000,0.0,-18.0,0.0,19.000000,19.0
100033,-195,-195,-195.000000,NaN,913.0,913.0,913.000000,-169.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,-6.0,0.0,7.000000,7.0
100035,-2723,-184,-1399.333333,1.151070e+06,-2539.0,9980.0,487.000000,-915.333333,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100036,-889,-889,-889.000000,NaN,-462.0,-462.0,-462.000000,-519.000000,0,0.0,...,0.000,NaN,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456220,-1594,-406,-1000.800000,3.091797e+05,-1410.0,27526.0,5134.000000,-458.800000,0,0.0,...,0.000,86326.7175,172653.435,NaN,NaN,2.0,NaN,NaN,NaN,0.0
456221,-1337,-113,-727.200000,3.131932e+05,-604.0,793.0,7.000000,-282.200000,0,0.0,...,0.000,NaN,0.000,17257.500,14901.7500,0.0,-19.0,0.0,15.000000,30.0
456223,-1017,-218,-539.000000,1.453435e+05,-701.0,-13.0,-382.250000,-308.400000,0,0.0,...,0.000,29202.7500,29202.750,5053.500,5053.5000,0.0,-7.0,0.0,8.000000,8.0
456224,-2738,-515,-1755.823529,6.669659e+05,-2497.0,980.0,-865.875000,-907.823529,0,0.0,...,0.000,0.0000,0.000,27531.000,10810.5000,0.0,-44.0,0.0,36.166667,217.0
456225,-1813,-354,-1053.000000,4.130155e+05,-1083.0,1470.0,253.125000,-174.333333,0,0.0,...,0.000,14186.9520,70934.760,NaN,NaN,0.0,-51.0,0.0,26.000000,156.0
456226,-748,-162,-455.000000,1.716980e+05,-24.0,1052.0,514.000000,-15.500000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,-24.0,0.0,15.500000,31.0
456227,-2413,-802,-1596.250000,4.575549e+05,-2076.0,779.0,-726.250000,-964.250000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456229,-1839,-1839,-1839.000000,NaN,9118.0,9118.0,9118.000000,-43.000000,0,0.0,...,0.000,NaN,0.000,NaN,NaN,1.0,NaN,NaN,NaN,0.0
456230,-2102,-606,-1254.833333,3.656416e+05,-1797.0,27336.0,2025.200000,-626.000000,12,1.0,...,52.875,0.0000,0.000,22500.000,18000.0000,0.0,-39.0,0.0,25.000000,100.0
456231,-1817,-12,-712.285714,4.000196e+05,-1483.0,2255.0,536.714286,-190.142857,0,0.0,...,0.000,0.0000,0.000,3838.500,3838.5000,0.0,-9.0,0.0,6.666667,20.0
456232,-764,-295,-529.500000,1.099805e+05,435.0,577.0,506.000000,-28.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456233,-203,-203,-203.000000,NaN,528.0,528.0,528.000000,-20.000000,0,0.0,...,0.000,0.0000,0.000,7537.500,7537.5000,0.0,-6.0,0.0,7.000000,7.0
456234,-1201,-21,-756.600000,2.127812e+05,-1047.0,1250.0,-205.100000,-507.300000,0,0.0,...,0.000,192.8925,385.785,13125.015,13125.0150,0.0,-36.0,0.0,11.000000,33.0
456235,-2754,-918,-1785.000000,8.505270e+05,-927.0,5622.0,1381.333333,-727.666667,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,-55.0,-10.0,46.000000,46.0
456236,-2772,-204,-1270.153846,1.026526e+06,-2407.0,10447.0,478.769231,-946.153846,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456237,-1430,-1430,-1430.000000,NaN,-699.0,-699.0,-699.000000,-1090.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456238,-2871,-593,-2157.833333,9.018746e+05,-2687.0,472.0,-1561.666667,-1579.333333,0,0.0,...,0.000,0.0000,0.000,0.000,0.0000,0.0,-45.0,0.0,33.000000,66.0
456239,-2835,-195,-1529.909091,7.495137e+05,-2470.0,10294.0,333.000000,-770.000000,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456240,-2653,-224,-1438.500000,2.950020e+06,-2467.0,27317.0,12425.000000,-1238.500000,0,0.0,...,0.000,50127.7500,50127.750,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456241,-2488,-314,-1599.200000,1.095059e+06,-2027.0,-1392.0,-1623.000000,-1096.600000,0,0.0,...,0.000,NaN,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456242,-491,-491,-491.000000,NaN,509.0,509.0,509.000000,-5.000000,0,0.0,...,0.000,0.0000,0.000,11205.000,11205.0000,0.0,-16.0,0.0,17.000000,17.0
456243,-2358,-154,-710.571429,5.803183e+05,-2167.0,452.0,-459.400000,-338.285714,0,0.0,...,0.000,NaN,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456244,-2906,-204,-1740.956522,7.039655e+05,-2759.0,1065.0,-1132.090909,-1209.826087,0,0.0,...,0.000,267.3225,534.645,47457.000,41193.0000,0.0,-95.0,0.0,34.000000,136.0
456246,-2141,-154,-1361.000000,1.123789e+06,-1594.0,852.0,-234.666667,-373.333333,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456247,-2482,-287,-1043.181818,6.126490e+05,-2299.0,10617.0,1449.818182,-768.818182,0,0.0,...,0.000,0.0000,0.000,4329.000,2164.5000,0.0,-23.0,0.0,15.666667,47.0
456249,-2713,-483,-1667.076923,4.073022e+05,-2499.0,1363.0,-1232.333333,-1064.538462,0,0.0,...,0.000,0.0000,0.000,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456250,-1002,-760,-862.000000,1.572400e+04,-272.0,2340.0,1288.333333,-60.333333,0,0.0,...,0.000,29134.1925,58268.385,51799.500,39778.4475,0.0,-27.0,0.0,27.000000,54.0
456253,-919,-713,-867.500000,1.060900e+04,-189.0,1113.0,280.500000,-253.250000,0,0.0,...,0.000,0.0000,0.000,58369.500,58369.5000,0.0,-30.0,0.0,27.500000,55.0
456254,-1104,-1104,-1104.000000,NaN,-859.0,-859.0,-859.000000,-401.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456255,-2337,-363,-1089.454545,5.027867e+05,-1243.0,27320.0,3231.272727,-531.090909,0,0.0,...,0.000,0.0000,0.000,3244.500,811.1250,0.0,-33.0,0.0,18.600000,93.0

In [52]:
del active, active_agg

In [53]:
gc.collect()

35

### Bureau: Closed credits - using only numerical aggregations

In [54]:
closed = bureau[bureau['CREDIT_ACTIVE_Closed'] == 1]

In [55]:
closed_agg = closed.groupby('SK_ID_CURR').agg(num_aggregations)
closed_agg

           DAYS_CREDIT                                  DAYS_CREDIT_ENDDATE  \
                   min   max         mean           var                 min
SK_ID_CURR
100001           -1572  -857 -1054.250000  1.195943e+05             -1329.0
100002           -1437  -476  -974.500000  1.239567e+05             -1072.0
100003           -2586  -775 -1665.666667  8.205903e+05             -2434.0
100004           -1326  -408  -867.000000  4.213620e+05              -595.0
100005            -373  -373  -373.000000           NaN              -128.0
100007           -1149 -1149 -1149.000000           NaN              -783.0
100008           -1097 -1097 -1097.000000  0.000000e+00              -853.0
100009           -2882  -684 -1465.714286  3.439544e+05             -2152.0
100010           -2741 -2741 -2741.000000           NaN              -928.0
100011           -2508 -1309 -1773.000000  3.334180e+05             -2173.0
100013           -2070 -1210 -1737.500000  1.552083e+05             -1707.0
100014           -2308  -435 -1327.333333  4.548291e+05             -2004.0
100015           -1409  -319  -947.750000  2.073689e+05             -1045.0
100016           -1634  -528 -1218.666667  3.626653e+05             -1369.0
100017           -2881  -909 -1944.333333  5.387127e+05             -2546.0
100020            -492  -288  -390.000000  2.080800e+04              -311.0
100023           -2624  -508 -1174.666667  3.796430e+05             -2228.0
100026           -1644 -1644 -1644.000000           NaN                 NaN
100027           -1983  -253 -1118.000000  1.496450e+06             -1649.0
100028           -2105  -992 -1652.714286  2.248872e+05             -1862.0
100029           -2806 -1375 -1852.333333  6.821103e+05             -1286.0
100030           -1547  -462 -1028.500000  2.270763e+05             -1173.0
100031           -1365  -203  -765.250000  2.656896e+05              -269.0
100032           -1389  -951 -1242.666667  6.380233e+04              -662.0
100035           -2723 -2159 -2496.250000  5.812625e+04             -2539.0
100037           -2761 -1247 -1862.285714  2.933432e+05             -2608.0
100039           -1485  -465  -787.400000  1.721193e+05             -1406.0
100041           -2890   -66 -1362.916667  8.751355e+05             -2678.0
100042           -2723  -262 -1746.500000  8.886579e+05             -1627.0
100043           -2639 -1169 -1904.000000  1.080450e+06             -2453.0
...                ...   ...          ...           ...                 ...
456215           -2624  -425 -1486.333333  8.188771e+05             -2440.0
456216           -1668 -1374 -1479.666667  2.673433e+04             -1303.0
456217           -1783 -1535 -1642.250000  1.584625e+04             -1446.0
456218           -1850  -714 -1112.750000  2.800769e+05             -1516.0
456219           -1450  -227  -842.400000  2.274583e+05             -1269.0
456220           -1594  -760 -1315.666667  2.315743e+05             -1410.0
456221           -1337  -113  -910.666667  4.779603e+05              -604.0
456223           -1017  -218  -616.500000  1.537497e+05              -701.0
456224           -2738  -515 -2125.818182  6.239876e+05             -2497.0
456225           -1813  -602 -1400.000000  4.777990e+05             -1083.0
456227           -2413  -802 -1607.500000  1.297660e+06             -2076.0
456230           -2102  -754 -1484.000000  3.612846e+05             -1797.0
456231           -1817  -471 -1102.000000  3.109713e+05             -1483.0
456234           -1201   -62  -835.857143  1.944541e+05             -1047.0
456235           -2754  -918 -1836.000000  1.685448e+06              -927.0
456236           -2772  -218 -1691.666667  8.836715e+05             -2407.0
456237           -1430 -1430 -1430.000000           NaN              -699.0
456238           -2871 -2579 -2745.250000  2.149092e+04             -2687.0
456239           -2835  -709 -1984.500000  6.245699e+05             -2470.0
456240           -2653 -2653 -2653.000000           NaN             -2467.0
456241           -2488  -314 -1139.666667  1.386454e+06             -1392.0
456243           -2358  -263  -911.400000  6.925393e+05             -2167.0
456244           -2815  -400 -1789.736842  5.167880e+05             -2759.0
456246           -2141 -1788 -1964.500000  6.230450e+04             -1594.0
456247           -2482  -287 -1264.250000  6.560502e+05             -2299.0
456249           -2713  -903 -1688.818182  2.587510e+05             -2499.0
456250           -1002 -1002 -1002.000000           NaN              -272.0
456253            -919  -919  -919.000000  0.000000e+00              -189.0
456254           -1104 -1104 -1104.000000           NaN              -859.0
456255           -2337  -970 -1533.166667  4.267014e+05             -1243.0

                                DAYS_CREDIT_UPDATE CREDIT_DAY_OVERDUE       \
               max         mean               mean                max mean
SK_ID_CURR
100001      -179.0  -628.500000        -155.000000                  0  0.0
100002        85.0  -574.800000        -661.333333                  0  0.0
100003      -420.0 -1131.333333       -1073.666667                  0  0.0
100004      -382.0  -488.500000        -532.000000                  0  0.0
100005      -128.0  -128.000000        -121.000000                  0  0.0
100007      -783.0  -783.000000        -783.000000                  0  0.0
100008      -792.0  -822.500000        -908.500000                  0  0.0
100009      1044.0  -993.714286       -1024.714286                  0  0.0
100010      -928.0  -928.000000       -1138.000000                  0  0.0
100011      -860.0 -1293.250000       -1454.750000                  0  0.0
100013      -567.0 -1068.000000        -775.500000                  0  0.0
100014        45.0  -754.333333        -811.333333                  0  0.0
100015       -16.0  -598.250000        -551.250000                  0  0.0
100016      -347.0 -1015.666667        -927.000000                  0  0.0
100017       197.0 -1512.333333       -1594.333333                  0  0.0
100020      -104.0  -207.500000        -221.500000                  0  0.0
100023      1318.0  -703.875000        -837.222222                  0  0.0
100026         NaN          NaN        -914.000000                  0  0.0
100027      -130.0  -889.500000        -899.500000                  0  0.0
100028      -452.0 -1269.000000        -946.285714                  0  0.0
100029      1563.0  -336.333333       -1383.333333                  0  0.0
100030       238.0  -429.250000        -609.750000                  0  0.0
100031       960.0   330.500000        -442.750000                  0  0.0
100032      -586.0  -636.666667        -564.333333                  0  0.0
100035     -1860.0 -2145.500000       -2018.000000                  0  0.0
100037     -1063.0 -1696.428571       -1623.285714                  0  0.0
100039      1256.0  -351.000000        -634.200000                  0  0.0
100041       117.0 -1045.500000       -1039.000000                  0  0.0
100042      1669.0  -480.500000       -1039.500000                  0  0.0
100043      -414.0 -1433.500000       -1320.000000                  0  0.0
...            ...          ...                ...                ...  ...
456215      1021.0  -939.500000        -928.500000                  0  0.0
456216      -643.0 -1013.000000        -767.000000                  0  0.0
456217      -532.0  -941.750000        -641.250000                  0  0.0
456218       412.0  -382.000000        -836.750000                  0  0.0
456219       169.0  -495.200000        -577.600000                  0  0.0
456220      -456.0 -1092.000000        -744.333333                  0  0.0
456221       -98.0  -417.666667        -452.000000                  0  0.0
456223       -13.0  -382.250000        -374.250000                  0  0.0
456224      -149.0 -1555.909091       -1390.727273                  0  0.0
456225      -689.0  -886.000000        -498.000000                  0  0.0
456227      -438.0 -1257.000000       -1302.000000                  0  0.0
456230      -428.0 -1188.142857        -875.625000                  0  0.0
456231      1355.0   -15.750000        -323.000000                  0  0.0
456234      1070.0  -408.428571        -627.714286                  0  0.0
456235      -551.0  -739.000000        -441.000000                  0  0.0
456236      1608.0  -687.333333       -1343.111111                  0  0.0
456237      -699.0  -699.000000       -1090.000000                  0  0.0
456238     -2395.0 -2569.250000       -2361.750000                  0  0.0
456239       386.0 -1436.000000       -1387.333333                  0  0.0
456240     -2467.0 -2467.000000       -2463.000000                  0  0.0
456241     -1392.0 -1392.000000        -661.666667                  0  0.0
456243       452.0  -459.400000        -453.400000                  0  0.0
456244       696.0 -1229.444444       -1310.157895                  0  0.0
456246        38.0  -778.000000        -537.000000                  0  0.0
456247      1458.0  -804.875000       -1048.125000                  0  0.0
456249      -658.0 -1465.400000       -1146.727273                  0  0.0
456250      -272.0  -272.000000        -127.000000                  0  0.0
456253      -189.0  -189.000000        -414.500000                  0  0.0
456254      -859.0  -859.000000        -401.000000                  0  0.0
456255      8620.0   858.833333        -954.000000                  0  0.0

            ...   AMT_CREDIT_SUM_OVERDUE AMT_CREDIT_SUM_LIMIT       \
            ...                     mean                 mean  sum
SK_ID_CURR  ...
100001      ...                      0.0                  0.0  0.0
100002      ...                      0.0                  0.0  0.0
100003      ...                      0.0                  0.0  0.0
100004      ...                      0.0                  0.0  0.0
100005      ...                      0.0                  0.0  0.0
100007      ...                      0.0                  0.0  0.0
100008      ...                      0.0                  0.0  0.0
100009      ...                      0.0                  0.0  0.0
100010      ...                      0.0                  NaN  0.0
100011      ...                      0.0                  0.0  0.0
100013      ...                      0.0                  NaN  0.0
100014      ...                      0.0                  0.0  0.0
100015      ...                      0.0                  0.0  0.0
100016      ...                      0.0                  0.0  0.0
100017      ...                      0.0                  0.0  0.0
100020      ...                      0.0                  0.0  0.0
100023      ...                      0.0                  0.0  0.0
100026      ...                      0.0                  NaN  0.0
100027      ...                      0.0                  0.0  0.0
100028      ...                      0.0                  0.0  0.0
100029      ...                      0.0                  0.0  0.0
100030      ...                      0.0                  0.0  0.0
100031      ...                      0.0                  NaN  0.0
100032      ...                      0.0                  0.0  0.0
100035      ...                      0.0                  0.0  0.0
100037      ...                      0.0                  0.0  0.0
100039      ...                      0.0                  NaN  0.0
100041      ...                      0.0                  0.0  0.0
100042      ...                      0.0                  0.0  0.0
100043      ...                      0.0                  0.0  0.0
...         ...                      ...                  ...  ...
456215      ...                      0.0                  0.0  0.0
456216      ...                      0.0                  0.0  0.0
456217      ...                      0.0                  0.0  0.0
456218      ...                      0.0                  0.0  0.0
456219      ...                      0.0                  0.0  0.0
456220      ...                      0.0                  0.0  0.0
456221      ...                      0.0                  0.0  0.0
456223      ...                      0.0                  0.0  0.0
456224      ...                      0.0                  0.0  0.0
456225      ...                      0.0                  0.0  0.0
456227      ...                      0.0                  0.0  0.0
456230      ...                      0.0                  0.0  0.0
456231      ...                      0.0                  0.0  0.0
456234      ...                      0.0                  0.0  0.0
456235      ...                      0.0                  0.0  0.0
456236      ...                      0.0                  0.0  0.0
456237      ...                      0.0                  0.0  0.0
456238      ...                      0.0                  0.0  0.0
456239      ...                      0.0                  0.0  0.0
456240      ...                      0.0                  NaN  0.0
456241      ...                      0.0                  0.0  0.0
456243      ...                      0.0                  0.0  0.0
456244      ...                      0.0                  0.0  0.0
456246      ...                      0.0                  0.0  0.0
456247      ...                      0.0                  0.0  0.0
456249      ...                      0.0                  0.0  0.0
456250      ...                      0.0                  0.0  0.0
456253      ...                      0.0                  0.0  0.0
456254      ...                      0.0                  NaN  0.0
456255      ...                      0.0                  0.0  0.0

           AMT_ANNUITY                CNT_CREDIT_PROLONG MONTHS_BALANCE_MIN  \
                   max           mean                sum                min
SK_ID_CURR
100001           0.000       0.000000                  0              -51.0
100002           0.000       0.000000                  0              -47.0
100003             NaN            NaN                  0                NaN
100004             NaN            NaN                  0                NaN
100005           0.000       0.000000                  0              -12.0
100007             NaN            NaN                  0                NaN
100008             NaN            NaN                  0                NaN
100009             NaN            NaN                  0                NaN
100010             NaN            NaN                  0              -90.0
100011             NaN            NaN                  0                NaN
100013           0.000       0.000000                  0              -68.0
100014             NaN            NaN                  0                NaN
100015             NaN            NaN                  0                NaN
100016             NaN            NaN                  0                NaN
100017             NaN            NaN                  0                NaN
100020             NaN            NaN                  0                NaN
100023             NaN            NaN                  0                NaN
100026             NaN            NaN                  0                NaN
100027             NaN            NaN                  0                NaN
100028           0.000       0.000000                  0              -69.0
100029             NaN            NaN                  0                NaN
100030             NaN            NaN                  0                NaN
100031             NaN            NaN                  0                NaN
100032       17437.500   17437.500000                  0              -45.0
100035             NaN            NaN                  0                NaN
100037           0.000       0.000000                  0              -90.0
100039             NaN            NaN                  0                NaN
100041             NaN            NaN                  0                NaN
100042           0.000       0.000000                  0              -89.0
100043       16290.000   16290.000000                  0              -86.0
...                ...            ...                ...                ...
456215        6484.500    3242.250000                  0              -86.0
456216             NaN            NaN                  0                NaN
456217       44140.500   44140.500000                  0              -58.0
456218       19125.000   19125.000000                  0              -60.0
456219       26775.000    6693.750000                  0              -47.0
456220             NaN            NaN                  0                NaN
456221           0.000       0.000000                  0              -43.0
456223           0.000       0.000000                  0              -33.0
456224       13653.000    1950.428571                  0              -89.0
456225             NaN            NaN                  0              -59.0
456227             NaN            NaN                  0                NaN
456230       29217.600   14657.400000                  0              -69.0
456231       25825.500   25825.500000                  0              -59.0
456234       13125.015   13125.015000                  0              -39.0
456235             NaN            NaN                  0              -90.0
456236             NaN            NaN                  0                NaN
456237             NaN            NaN                  0                NaN
456238       19800.000   19800.000000                  0              -94.0
456239             NaN            NaN                  0                NaN
456240             NaN            NaN                  0                NaN
456241             NaN            NaN                  0                NaN
456243             NaN            NaN                  0                NaN
456244           0.000       0.000000                  0              -92.0
456246             NaN            NaN                  0                NaN
456247       26275.500    7852.500000                  1              -81.0
456249             NaN            NaN                  0                NaN
456250      384147.000  384147.000000                  0              -32.0
456253       58369.500   58369.500000                  0              -30.0
456254           0.000       0.000000                  0              -36.0
456255        3244.500    1297.800000                  1              -76.0

           MONTHS_BALANCE_MAX MONTHS_BALANCE_SIZE
                          max                mean    sum
SK_ID_CURR
100001                    0.0           35.000000  140.0
100002                    0.0           15.000000   90.0
100003                    NaN                 NaN    0.0
100004                    NaN                 NaN    0.0
100005                    0.0           13.000000   13.0
100007                    NaN                 NaN    0.0
100008                    NaN                 NaN    0.0
100009                    NaN                 NaN    0.0
100010                  -55.0           36.000000   36.0
100011                    NaN                 NaN    0.0
100013                    0.0           57.500000  230.0
100014                    NaN                 NaN    0.0
100015                    NaN                 NaN    0.0
100016                    NaN                 NaN    0.0
100017                    NaN                 NaN    0.0
100020                    NaN                 NaN    0.0
100023                    NaN                 NaN    0.0
100026                    NaN                 NaN    0.0
100027                    NaN                 NaN    0.0
100028                    0.0           55.000000  385.0
100029                    NaN                 NaN    0.0
100030                    NaN                 NaN    0.0

In [56]:
closed_agg.columns = pd.Index(['CLOSED_' + e[0] + "_" + e[1].upper() for e in closed_agg.columns.tolist()])
closed_agg

,CLOSED_DAYS_CREDIT_MIN,CLOSED_DAYS_CREDIT_MAX,CLOSED_DAYS_CREDIT_MEAN,CLOSED_DAYS_CREDIT_VAR,CLOSED_DAYS_CREDIT_ENDDATE_MIN,CLOSED_DAYS_CREDIT_ENDDATE_MAX,CLOSED_DAYS_CREDIT_ENDDATE_MEAN,CLOSED_DAYS_CREDIT_UPDATE_MEAN,CLOSED_CREDIT_DAY_OVERDUE_MAX,CLOSED_CREDIT_DAY_OVERDUE_MEAN,...,CLOSED_AMT_CREDIT_SUM_OVERDUE_MEAN,CLOSED_AMT_CREDIT_SUM_LIMIT_MEAN,CLOSED_AMT_CREDIT_SUM_LIMIT_SUM,CLOSED_AMT_ANNUITY_MAX,CLOSED_AMT_ANNUITY_MEAN,CLOSED_CNT_CREDIT_PROLONG_SUM,CLOSED_MONTHS_BALANCE_MIN_MIN,CLOSED_MONTHS_BALANCE_MAX_MAX,CLOSED_MONTHS_BALANCE_SIZE_MEAN,CLOSED_MONTHS_BALANCE_SIZE_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,-1572,-857,-1054.250000,1.195943e+05,-1329.0,-179.0,-628.500000,-155.000000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-51.0,0.0,35.000000,140.0
100002,-1437,-476,-974.500000,1.239567e+05,-1072.0,85.0,-574.800000,-661.333333,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-47.0,0.0,15.000000,90.0
100003,-2586,-775,-1665.666667,8.205903e+05,-2434.0,-420.0,-1131.333333,-1073.666667,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100004,-1326,-408,-867.000000,4.213620e+05,-595.0,-382.0,-488.500000,-532.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100005,-373,-373,-373.000000,NaN,-128.0,-128.0,-128.000000,-121.000000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-12.0,0.0,13.000000,13.0
100007,-1149,-1149,-1149.000000,NaN,-783.0,-783.0,-783.000000,-783.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100008,-1097,-1097,-1097.000000,0.000000e+00,-853.0,-792.0,-822.500000,-908.500000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100009,-2882,-684,-1465.714286,3.439544e+05,-2152.0,1044.0,-993.714286,-1024.714286,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100010,-2741,-2741,-2741.000000,NaN,-928.0,-928.0,-928.000000,-1138.000000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0,-90.0,-55.0,36.000000,36.0
100011,-2508,-1309,-1773.000000,3.334180e+05,-2173.0,-860.0,-1293.250000,-1454.750000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100013,-2070,-1210,-1737.500000,1.552083e+05,-1707.0,-567.0,-1068.000000,-775.500000,0,0.0,...,0.0,NaN,0.0,0.000,0.000000,0,-68.0,0.0,57.500000,230.0
100014,-2308,-435,-1327.333333,4.548291e+05,-2004.0,45.0,-754.333333,-811.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100015,-1409,-319,-947.750000,2.073689e+05,-1045.0,-16.0,-598.250000,-551.250000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100016,-1634,-528,-1218.666667,3.626653e+05,-1369.0,-347.0,-1015.666667,-927.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100017,-2881,-909,-1944.333333,5.387127e+05,-2546.0,197.0,-1512.333333,-1594.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100020,-492,-288,-390.000000,2.080800e+04,-311.0,-104.0,-207.500000,-221.500000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100023,-2624,-508,-1174.666667,3.796430e+05,-2228.0,1318.0,-703.875000,-837.222222,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100026,-1644,-1644,-1644.000000,NaN,NaN,NaN,NaN,-914.000000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100027,-1983,-253,-1118.000000,1.496450e+06,-1649.0,-130.0,-889.500000,-899.500000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100028,-2105,-992,-1652.714286,2.248872e+05,-1862.0,-452.0,-1269.000000,-946.285714,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-69.0,0.0,55.000000,385.0
100029,-2806,-1375,-1852.333333,6.821103e+05,-1286.0,1563.0,-336.333333,-1383.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100030,-1547,-462,-1028.500000,2.270763e+05,-1173.0,238.0,-429.250000,-609.750000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100031,-1365,-203,-765.250000,2.656896e+05,-269.0,960.0,330.500000,-442.750000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100032,-1389,-951,-1242.666667,6.380233e+04,-662.0,-586.0,-636.666667,-564.333333,0,0.0,...,0.0,0.0,0.0,17437.500,17437.500000,0,-45.0,-13.0,19.000000,57.0
100035,-2723,-2159,-2496.250000,5.812625e+04,-2539.0,-1860.0,-2145.500000,-2018.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100037,-2761,-1247,-1862.285714,2.933432e+05,-2608.0,-1063.0,-1696.428571,-1623.285714,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-90.0,0.0,53.142857,372.0
100039,-1485,-465,-787.400000,1.721193e+05,-1406.0,1256.0,-351.000000,-634.200000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100041,-2890,-66,-1362.916667,8.751355e+05,-2678.0,117.0,-1045.500000,-1039.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
100042,-2723,-262,-1746.500000,8.886579e+05,-1627.0,1669.0,-480.500000,-1039.500000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-89.0,0.0,57.833333,347.0
100043,-2639,-1169,-1904.000000,1.080450e+06,-2453.0,-414.0,-1433.500000,-1320.000000,0,0.0,...,0.0,0.0,0.0,16290.000,16290.000000,0,-86.0,-37.0,2.000000,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456215,-2624,-425,-1486.333333,8.188771e+05,-2440.0,1021.0,-939.500000,-928.500000,0,0.0,...,0.0,0.0,0.0,6484.500,3242.250000,0,-86.0,0.0,32.000000,192.0
456216,-1668,-1374,-1479.666667,2.673433e+04,-1303.0,-643.0,-1013.000000,-767.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456217,-1783,-1535,-1642.250000,1.584625e+04,-1446.0,-532.0,-941.750000,-641.250000,0,0.0,...,0.0,0.0,0.0,44140.500,44140.500000,0,-58.0,0.0,33.000000,132.0
456218,-1850,-714,-1112.750000,2.800769e+05,-1516.0,412.0,-382.000000,-836.750000,0,0.0,...,0.0,0.0,0.0,19125.000,19125.000000,0,-60.0,-9.0,15.000000,60.0
456219,-1450,-227,-842.400000,2.274583e+05,-1269.0,169.0,-495.200000,-577.600000,0,0.0,...,0.0,0.0,0.0,26775.000,6693.750000,0,-47.0,0.0,24.400000,122.0
456220,-1594,-760,-1315.666667,2.315743e+05,-1410.0,-456.0,-1092.000000,-744.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456221,-1337,-113,-910.666667,4.779603e+05,-604.0,-98.0,-417.666667,-452.000000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-43.0,0.0,30.333333,91.0
456223,-1017,-218,-616.500000,1.537497e+05,-701.0,-13.0,-382.250000,-374.250000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-33.0,0.0,21.000000,84.0
456224,-2738,-515,-2125.818182,6.239876e+05,-2497.0,-149.0,-1555.909091,-1390.727273,0,0.0,...,0.0,0.0,0.0,13653.000,1950.428571,0,-89.0,0.0,70.181818,772.0
456225,-1813,-602,-1400.000000,4.777990e+05,-1083.0,-689.0,-886.000000,-498.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,-59.0,0.0,38.333333,115.0
456227,-2413,-802,-1607.500000,1.297660e+06,-2076.0,-438.0,-1257.000000,-1302.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456230,-2102,-754,-1484.000000,3.612846e+05,-1797.0,-428.0,-1188.142857,-875.625000,0,0.0,...,0.0,0.0,0.0,29217.600,14657.400000,0,-69.0,0.0,35.625000,285.0
456231,-1817,-471,-1102.000000,3.109713e+05,-1483.0,1355.0,-15.750000,-323.000000,0,0.0,...,0.0,0.0,0.0,25825.500,25825.500000,0,-59.0,0.0,18.000000,72.0
456234,-1201,-62,-835.857143,1.944541e+05,-1047.0,1070.0,-408.428571,-627.714286,0,0.0,...,0.0,0.0,0.0,13125.015,13125.015000,0,-39.0,0.0,14.000000,98.0
456235,-2754,-918,-1836.000000,1.685448e+06,-927.0,-551.0,-739.000000,-441.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,-90.0,0.0,38.500000,77.0
456236,-2772,-218,-1691.666667,8.836715e+05,-2407.0,1608.0,-687.333333,-1343.111111,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456237,-1430,-1430,-1430.000000,NaN,-699.0,-699.0,-699.000000,-1090.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456238,-2871,-2579,-2745.250000,2.149092e+04,-2687.0,-2395.0,-2569.250000,-2361.750000,0,0.0,...,0.0,0.0,0.0,19800.000,19800.000000,0,-94.0,0.0,89.000000,356.0
456239,-2835,-709,-1984.500000,6.245699e+05,-2470.0,386.0,-1436.000000,-1387.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456240,-2653,-2653,-2653.000000,NaN,-2467.0,-2467.0,-2467.000000,-2463.000000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456241,-2488,-314,-1139.666667,1.386454e+06,-1392.0,-1392.0,-1392.000000,-661.666667,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456243,-2358,-263,-911.400000,6.925393e+05,-2167.0,452.0,-459.400000,-453.400000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456244,-2815,-400,-1789.736842,5.167880e+05,-2759.0,696.0,-1229.444444,-1310.157895,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0,-92.0,0.0,51.684211,982.0
456246,-2141,-1788,-1964.500000,6.230450e+04,-1594.0,38.0,-778.000000,-537.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456247,-2482,-287,-1264.250000,6.560502e+05,-2299.0,1458.0,-804.875000,-1048.125000,0,0.0,...,0.0,0.0,0.0,26275.500,7852.500000,1,-81.0,0.0,34.125000,273.0
456249,-2713,-903,-1688.818182,2.587510e+05,-2499.0,-658.0,-1465.400000,-1146.727273,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0,NaN,NaN,NaN,0.0
456250,-1002,-1002,-1002.000000,NaN,-272.0,-272.0,-272.000000,-127.000000,0,0.0,...,0.0,0.0,0.0,384147.000,384147.000000,0,-32.0,0.0,33.000000,33.0
456253,-919,-919,-919.000000,0.000000e+00,-189.0,-189.0,-189.000000,-414.500000,0,0.0,...,0.0,0.0,0.0,58369.500,58369.500000,0,-30.0,0.0,31.000000,62.0
456254,-1104,-1104,-1104.000000,NaN,-859.0,-859.0,-859.000000,-401.000000,0,0.0,...,0.0,NaN,0.0,0.000,0.000000,0,-36.0,0.0,37.000000,37.0
456255,-2337,-970,-1533.166667,4.267014e+05,-1243.0,8620.0,858.833333,-954.000000,0,0.0,...,0.0,0.0,0.0,3244.500,1297.800000,1,-76.0,0.0,33.333333,200.0

In [57]:
bureau_agg = bureau_agg.join(closed_agg, how='left', on='SK_ID_CURR')

In [58]:
bureau_agg

,BURO_DAYS_CREDIT_MIN,BURO_DAYS_CREDIT_MAX,BURO_DAYS_CREDIT_MEAN,BURO_DAYS_CREDIT_VAR,BURO_DAYS_CREDIT_ENDDATE_MIN,BURO_DAYS_CREDIT_ENDDATE_MAX,BURO_DAYS_CREDIT_ENDDATE_MEAN,BURO_DAYS_CREDIT_UPDATE_MEAN,BURO_CREDIT_DAY_OVERDUE_MAX,BURO_CREDIT_DAY_OVERDUE_MEAN,...,CLOSED_AMT_CREDIT_SUM_OVERDUE_MEAN,CLOSED_AMT_CREDIT_SUM_LIMIT_MEAN,CLOSED_AMT_CREDIT_SUM_LIMIT_SUM,CLOSED_AMT_ANNUITY_MAX,CLOSED_AMT_ANNUITY_MEAN,CLOSED_CNT_CREDIT_PROLONG_SUM,CLOSED_MONTHS_BALANCE_MIN_MIN,CLOSED_MONTHS_BALANCE_MAX_MAX,CLOSED_MONTHS_BALANCE_SIZE_MEAN,CLOSED_MONTHS_BALANCE_SIZE_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,-1572,-49,-735.000000,2.400437e+05,-1329.0,1778.0,82.428571,-93.142857,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-51.0,0.0,35.000000,140.0
100002,-1437,-103,-874.000000,1.861500e+05,-1072.0,780.0,-349.000000,-499.875000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-47.0,0.0,15.000000,90.0
100003,-2586,-606,-1400.750000,8.277836e+05,-2434.0,1216.0,-544.500000,-816.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100004,-1326,-408,-867.000000,4.213620e+05,-595.0,-382.0,-488.500000,-532.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100005,-373,-62,-190.666667,2.634033e+04,-128.0,1324.0,439.333333,-54.333333,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-12.0,0.0,13.000000,13.0
100007,-1149,-1149,-1149.000000,NaN,-783.0,-783.0,-783.000000,-783.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100008,-1097,-78,-757.333333,3.461203e+05,-853.0,471.0,-391.333333,-611.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100009,-2882,-239,-1271.500000,4.426300e+05,-2152.0,1402.0,-794.937500,-851.611111,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100010,-2741,-1138,-1939.500000,1.284804e+06,-928.0,689.0,-119.500000,-578.000000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0.0,-90.0,-55.0,36.000000,36.0
100011,-2508,-1309,-1773.000000,3.334180e+05,-2173.0,-860.0,-1293.250000,-1454.750000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100013,-2070,-1210,-1737.500000,1.552083e+05,-1707.0,-567.0,-1068.000000,-775.500000,0,0.0,...,0.0,NaN,0.0,0.000,0.000000,0.0,-68.0,0.0,57.500000,230.0
100014,-2308,-376,-1095.375000,5.095088e+05,-2004.0,723.0,-387.375000,-615.875000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100015,-1409,-319,-947.750000,2.073689e+05,-1045.0,-16.0,-598.250000,-551.250000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100016,-1634,-128,-618.428571,4.381120e+05,-1369.0,845.0,-217.142857,-405.857143,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100017,-2881,-909,-1944.333333,5.387127e+05,-2546.0,197.0,-1512.333333,-1594.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100019,-495,-495,-495.000000,0.000000e+00,419.0,10463.0,5441.000000,-26.500000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100020,-492,-90,-261.500000,3.018500e+04,-311.0,277.0,-32.500000,-130.750000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100022,-385,-289,-337.000000,4.608000e+03,441.0,1439.0,940.000000,-28.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100023,-2624,-157,-1164.384615,4.625959e+05,-2228.0,1669.0,-364.916667,-634.076923,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100025,-700,-700,-700.000000,NaN,1124.0,1124.0,1124.000000,-49.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100026,-1644,-148,-679.000000,7.007710e+05,217.0,1581.0,899.000000,-314.666667,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100027,-1983,-143,-793.000000,1.065100e+06,-1649.0,944.0,-278.333333,-600.666667,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100028,-2105,-269,-1401.750000,4.303558e+05,-1862.0,30885.0,2387.700000,-651.500000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-69.0,0.0,55.000000,385.0
100029,-2806,-110,-1416.750000,1.213672e+06,-1286.0,1563.0,-336.333333,-1041.750000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100030,-1547,-418,-930.833333,1.994614e+05,-1173.0,1409.0,-61.600000,-411.166667,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100031,-1365,-75,-579.571429,2.292140e+05,-269.0,1021.0,468.600000,-266.285714,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100032,-1389,-556,-1071.000000,1.604127e+05,-662.0,-191.0,-525.250000,-436.750000,0,0.0,...,0.0,0.0,0.0,17437.500,17437.500000,0.0,-45.0,-13.0,19.000000,57.0
100033,-195,-195,-195.000000,NaN,913.0,913.0,913.000000,-169.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100035,-2723,-184,-1399.333333,1.151070e+06,-2539.0,9980.0,487.000000,-915.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
100036,-889,-889,-889.000000,NaN,-462.0,-462.0,-462.000000,-519.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456220,-1594,-406,-1000.800000,3.091797e+05,-1410.0,27526.0,5134.000000,-458.800000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456221,-1337,-113,-727.200000,3.131932e+05,-604.0,793.0,7.000000,-282.200000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-43.0,0.0,30.333333,91.0
456223,-1017,-218,-539.000000,1.453435e+05,-701.0,-13.0,-382.250000,-308.400000,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-33.0,0.0,21.000000,84.0
456224,-2738,-515,-1755.823529,6.669659e+05,-2497.0,980.0,-865.875000,-907.823529,0,0.0,...,0.0,0.0,0.0,13653.000,1950.428571,0.0,-89.0,0.0,70.181818,772.0
456225,-1813,-354,-1053.000000,4.130155e+05,-1083.0,1470.0,253.125000,-174.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,-59.0,0.0,38.333333,115.0
456226,-748,-162,-455.000000,1.716980e+05,-24.0,1052.0,514.000000,-15.500000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456227,-2413,-802,-1596.250000,4.575549e+05,-2076.0,779.0,-726.250000,-964.250000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456229,-1839,-1839,-1839.000000,NaN,9118.0,9118.0,9118.000000,-43.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456230,-2102,-606,-1254.833333,3.656416e+05,-1797.0,27336.0,2025.200000,-626.000000,12,1.0,...,0.0,0.0,0.0,29217.600,14657.400000,0.0,-69.0,0.0,35.625000,285.0
456231,-1817,-12,-712.285714,4.000196e+05,-1483.0,2255.0,536.714286,-190.142857,0,0.0,...,0.0,0.0,0.0,25825.500,25825.500000,0.0,-59.0,0.0,18.000000,72.0
456232,-764,-295,-529.500000,1.099805e+05,435.0,577.0,506.000000,-28.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456233,-203,-203,-203.000000,NaN,528.0,528.0,528.000000,-20.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456234,-1201,-21,-756.600000,2.127812e+05,-1047.0,1250.0,-205.100000,-507.300000,0,0.0,...,0.0,0.0,0.0,13125.015,13125.015000,0.0,-39.0,0.0,14.000000,98.0
456235,-2754,-918,-1785.000000,8.505270e+05,-927.0,5622.0,1381.333333,-727.666667,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,-90.0,0.0,38.500000,77.0
456236,-2772,-204,-1270.153846,1.026526e+06,-2407.0,10447.0,478.769231,-946.153846,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456237,-1430,-1430,-1430.000000,NaN,-699.0,-699.0,-699.000000,-1090.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456238,-2871,-593,-2157.833333,9.018746e+05,-2687.0,472.0,-1561.666667,-1579.333333,0,0.0,...,0.0,0.0,0.0,19800.000,19800.000000,0.0,-94.0,0.0,89.000000,356.0
456239,-2835,-195,-1529.909091,7.495137e+05,-2470.0,10294.0,333.000000,-770.000000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456240,-2653,-224,-1438.500000,2.950020e+06,-2467.0,27317.0,12425.000000,-1238.500000,0,0.0,...,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456241,-2488,-314,-1599.200000,1.095059e+06,-2027.0,-1392.0,-1623.000000,-1096.600000,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456242,-491,-491,-491.000000,NaN,509.0,509.0,509.000000,-5.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456243,-2358,-154,-710.571429,5.803183e+05,-2167.0,452.0,-459.400000,-338.285714,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456244,-2906,-204,-1740.956522,7.039655e+05,-2759.0,1065.0,-1132.090909,-1209.826087,0,0.0,...,0.0,0.0,0.0,0.000,0.000000,0.0,-92.0,0.0,51.684211,982.0
456246,-2141,-154,-1361.000000,1.123789e+06,-1594.0,852.0,-234.666667,-373.333333,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456247,-2482,-287,-1043.181818,6.126490e+05,-2299.0,10617.0,1449.818182,-768.818182,0,0.0,...,0.0,0.0,0.0,26275.500,7852.500000,1.0,-81.0,0.0,34.125000,273.0
456249,-2713,-483,-1667.076923,4.073022e+05,-2499.0,1363.0,-1232.333333,-1064.538462,0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,0.0
456250,-1002,-760,-862.000000,1.572400e+04,-272.0,2340.0,1288.333333,-60.333333,0,0.0,...,0.0,0.0,0.0,384147.000,384147.000000,0.0,-32.0,0.0,33.000000,33.0
456253,-919,-713,-867.500000,1.060900e+04,-189.0,1113.0,280.500000,-253.250000,0,0.0,...,0.0,0.0,0.0,58369.500,58369.500000,0.0,-30.0,0.0,31.000000,62.0
456254,-1104,-1104,-1104.000000,NaN,-859.0,-859.0,-859.000000,-401.000000,0,0.0,...,0.0,NaN,0.0,0.000,0.000000,0.0,-36.0,0.0,37.000000,37.0
456255,-2337,-363,-1089.454545,5.027867e+05,-1243.0,27320.0,3231.272727,-531.090909,0,0.0,...,0.0,0.0,0.0,3244.500,1297.800000,1.0,-76.0,0.0,33.333333,200.0

In [59]:
for e in cols:
        bureau_agg['NEW_RATIO_BURO_' + e[0] + "_" + e[1].upper()] = bureau_agg['ACTIVE_' + e[0] + "_" + e[1].upper()] / bureau_agg['CLOSED_' + e[0] + "_" + e[1].upper()]

In [60]:
bureau_agg

,BURO_DAYS_CREDIT_MIN,BURO_DAYS_CREDIT_MAX,BURO_DAYS_CREDIT_MEAN,BURO_DAYS_CREDIT_VAR,BURO_DAYS_CREDIT_ENDDATE_MIN,BURO_DAYS_CREDIT_ENDDATE_MAX,BURO_DAYS_CREDIT_ENDDATE_MEAN,BURO_DAYS_CREDIT_UPDATE_MEAN,BURO_CREDIT_DAY_OVERDUE_MAX,BURO_CREDIT_DAY_OVERDUE_MEAN,...,NEW_RATIO_BURO_AMT_CREDIT_SUM_OVERDUE_MEAN,NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_MEAN,NEW_RATIO_BURO_AMT_CREDIT_SUM_LIMIT_SUM,NEW_RATIO_BURO_AMT_ANNUITY_MAX,NEW_RATIO_BURO_AMT_ANNUITY_MEAN,NEW_RATIO_BURO_CNT_CREDIT_PROLONG_SUM,NEW_RATIO_BURO_MONTHS_BALANCE_MIN_MIN,NEW_RATIO_BURO_MONTHS_BALANCE_MAX_MAX,NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_MEAN,NEW_RATIO_BURO_MONTHS_BALANCE_SIZE_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,-1572,-49,-735.000000,2.400437e+05,-1329.0,1778.0,82.428571,-93.142857,0,0.0,...,NaN,NaN,NaN,inf,inf,NaN,0.352941,NaN,0.304762,0.228571
100002,-1437,-103,-874.000000,1.861500e+05,-1072.0,780.0,-349.000000,-499.875000,0,0.0,...,NaN,inf,inf,NaN,NaN,NaN,0.723404,NaN,0.666667,0.222222
100003,-2586,-606,-1400.750000,8.277836e+05,-2434.0,1216.0,-544.500000,-816.000000,0,0.0,...,NaN,inf,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100004,-1326,-408,-867.000000,4.213620e+05,-595.0,-382.0,-488.500000,-532.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100005,-373,-62,-190.666667,2.634033e+04,-128.0,1324.0,439.333333,-54.333333,0,0.0,...,NaN,NaN,NaN,inf,inf,NaN,0.333333,NaN,0.307692,0.615385
100007,-1149,-1149,-1149.000000,NaN,-783.0,-783.0,-783.000000,-783.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100008,-1097,-78,-757.333333,3.461203e+05,-853.0,471.0,-391.333333,-611.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100009,-2882,-239,-1271.500000,4.426300e+05,-2152.0,1402.0,-794.937500,-851.611111,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100010,-2741,-1138,-1939.500000,1.284804e+06,-928.0,689.0,-119.500000,-578.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.411111,0.036364,1.000000,1.000000
100011,-2508,-1309,-1773.000000,3.334180e+05,-2173.0,-860.0,-1293.250000,-1454.750000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100013,-2070,-1210,-1737.500000,1.552083e+05,-1707.0,-567.0,-1068.000000,-775.500000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100014,-2308,-376,-1095.375000,5.095088e+05,-2004.0,723.0,-387.375000,-615.875000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100015,-1409,-319,-947.750000,2.073689e+05,-1045.0,-16.0,-598.250000,-551.250000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100016,-1634,-128,-618.428571,4.381120e+05,-1369.0,845.0,-217.142857,-405.857143,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100017,-2881,-909,-1944.333333,5.387127e+05,-2546.0,197.0,-1512.333333,-1594.333333,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100019,-495,-495,-495.000000,0.000000e+00,419.0,10463.0,5441.000000,-26.500000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100020,-492,-90,-261.500000,3.018500e+04,-311.0,277.0,-32.500000,-130.750000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100022,-385,-289,-337.000000,4.608000e+03,441.0,1439.0,940.000000,-28.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100023,-2624,-157,-1164.384615,4.625959e+05,-2228.0,1669.0,-364.916667,-634.076923,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100025,-700,-700,-700.000000,NaN,1124.0,1124.0,1124.000000,-49.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100026,-1644,-148,-679.000000,7.007710e+05,217.0,1581.0,899.000000,-314.666667,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100027,-1983,-143,-793.000000,1.065100e+06,-1649.0,944.0,-278.333333,-600.666667,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100028,-2105,-269,-1401.750000,4.303558e+05,-1862.0,30885.0,2387.700000,-651.500000,0,0.0,...,NaN,inf,inf,inf,inf,NaN,0.855072,NaN,0.636364,0.454545
100029,-2806,-110,-1416.750000,1.213672e+06,-1286.0,1563.0,-336.333333,-1041.750000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100030,-1547,-418,-930.833333,1.994614e+05,-1173.0,1409.0,-61.600000,-411.166667,0,0.0,...,NaN,inf,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100031,-1365,-75,-579.571429,2.292140e+05,-269.0,1021.0,468.600000,-266.285714,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100032,-1389,-556,-1071.000000,1.604127e+05,-662.0,-191.0,-525.250000,-436.750000,0,0.0,...,NaN,NaN,NaN,1.000000,1.000000,NaN,0.400000,-0.000000,1.000000,0.333333
100033,-195,-195,-195.000000,NaN,913.0,913.0,913.000000,-169.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100035,-2723,-184,-1399.333333,1.151070e+06,-2539.0,9980.0,487.000000,-915.333333,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100036,-889,-889,-889.000000,NaN,-462.0,-462.0,-462.000000,-519.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456220,-1594,-406,-1000.800000,3.091797e+05,-1410.0,27526.0,5134.000000,-458.800000,0,0.0,...,NaN,inf,inf,NaN,NaN,inf,NaN,NaN,NaN,NaN
456221,-1337,-113,-727.200000,3.131932e+05,-604.0,793.0,7.000000,-282.200000,0,0.0,...,NaN,NaN,NaN,inf,inf,NaN,0.441860,NaN,0.494505,0.329670
456223,-1017,-218,-539.000000,1.453435e+05,-701.0,-13.0,-382.250000,-308.400000,0,0.0,...,NaN,inf,inf,inf,inf,NaN,0.212121,NaN,0.380952,0.095238
456224,-2738,-515,-1755.823529,6.669659e+05,-2497.0,980.0,-865.875000,-907.823529,0,0.0,...,NaN,NaN,NaN,2.016480,5.542628,NaN,0.494382,NaN,0.515328,0.281088
456225,-1813,-354,-1053.000000,4.130155e+05,-1083.0,1470.0,253.125000,-174.333333,0,0.0,...,NaN,inf,inf,NaN,NaN,NaN,0.864407,NaN,0.678261,1.356522
456226,-748,-162,-455.000000,1.716980e+05,-24.0,1052.0,514.000000,-15.500000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456227,-2413,-802,-1596.250000,4.575549e+05,-2076.0,779.0,-726.250000,-964.250000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456229,-1839,-1839,-1839.000000,NaN,9118.0,9118.0,9118.000000,-43.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456230,-2102,-606,-1254.833333,3.656416e+05,-1797.0,27336.0,2025.200000,-626.000000,12,1.0,...,inf,NaN,NaN,0.770084,1.228049,NaN,0.565217,NaN,0.701754,0.350877
456231,-1817,-12,-712.285714,4.000196e+05,-1483.0,2255.0,536.714286,-190.142857,0,0.0,...,NaN,NaN,NaN,0.148632,0.148632,NaN,0.152542,NaN,0.370370,0.277778
456232,-764,-295,-529.500000,1.099805e+05,435.0,577.0,506.000000,-28.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456233,-203,-203,-203.000000,NaN,528.0,528.0,528.000000,-20.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456234,-1201,-21,-756.600000,2.127812e+05,-1047.0,1250.0,-205.100000,-507.300000,0,0.0,...,NaN,inf,inf,1.000000,1.000000,NaN,0.923077,NaN,0.785714,0.336735
456235,-2754,-918,-1785.000000,8.505270e+05,-927.0,5622.0,1381.333333,-727.666667,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.611111,-inf,1.194805,0.597403
456236,-2772,-204,-1270.153846,1.026526e+06,-2407.0,10447.0,478.769231,-946.153846,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456237,-1430,-1430,-1430.000000,NaN,-699.0,-699.0,-699.000000,-1090.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456238,-2871,-593,-2157.833333,9.018746e+05,-2687.0,472.0,-1561.666667,-1579.333333,0,0.0,...,NaN,NaN,NaN,0.000000,0.000000,NaN,0.478723,NaN,0.370787,0.185393
456239,-2835,-195,-1529.909091,7.495137e+05,-2470.0,10294.0,333.000000,-770.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456240,-2653,-224,-1438.500000,2.950020e+06,-2467.0,27317.0,12425.000000,-1238.500000,0,0.0,...,NaN,NaN,inf,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456241,-2488,-314,-1599.200000,1.095059e+06,-2027.0,-1392.0,-1623.000000,-1096.600000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456242,-491,-491,-491.000000,NaN,509.0,509.0,509.000000,-5.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456243,-2358,-154,-710.571429,5.803183e+05,-2167.0,452.0,-459.400000,-338.285714,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456244,-2906,-204,-1740.956522,7.039655e+05,-2759.0,1065.0,-1132.090909,-1209.826087,0,0.0,...,NaN,inf,inf,inf,inf,NaN,1.032609,NaN,0.657841,0.138493
456246,-2141,-154,-1361.000000,1.123789e+06,-1594.0,852.0,-234.666667,-373.333333,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456247,-2482,-287,-1043.181818,6.126490e+05,-2299.0,10617.0,1449.818182,-768.818182,0,0.0,...,NaN,NaN,NaN,0.164754,0.275645,0.000000,0.283951,NaN,0.459096,0.172161
456249,-2713,-483,-1667.076923,4.073022e+05,-2499.0,1363.0,-1232.333333,-1064.538462,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456250,-1002,-760,-862.000000,1.572400e+04,-272.0,2340.0,1288.333333,-60.333333,0,0.0,...,NaN,inf,inf,0.134843,0.103550,NaN,0.843750,NaN,0.818182,1.636364
456253,-919,-713,-867.500000,1.060900e+04,-189.0,1113.0,280.500000,-253.250000,0,0.0,...,NaN,NaN,NaN,1.000000,1.000000,NaN,1.000000,NaN,0.887097,0.887097
456254,-1104,-1104,-1104.000000,NaN,-859.0,-859.0,-859.000000,-401.000000,0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456255,-2337,-363,-1089.454545,5.027867e+05,-1243.0,27320.0,3231.272727,-531.090909,0,0.0,...,NaN,NaN,NaN,1.000000,0.625000,0.000000,0.434211,NaN,0.558000,0.465000

In [61]:
del closed, closed_agg, bureau

In [62]:
gc.collect()

14

# Preprocess application

In [38]:
df = pd.read_csv('../input/application_train.csv', nrows= None)
test_df = pd.read_csv('../input/application_test.csv', nrows= None)

In [39]:
print("Train samples: {}, test samples: {}".format(len(df), len(test_df)))

Train samples: 307511, test samples: 48744

### Optional: Remove 4 applications with XNA CODE_GENDER (train set)

In [40]:
df = df[df['CODE_GENDER'] != 'XNA']

In [41]:
docs = [_f for _f in df.columns if 'FLAG_DOC' in _f]

In [42]:
docs

['FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21']

In [43]:
live = [_f for _f in df.columns if ('FLAG_' in _f) & ('FLAG_DOC' not in _f) & ('_FLAG_' not in _f)]

In [44]:
live

['FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL']

### NaN values for DAYS_EMPLOYED: 365.243 -> nan

In [46]:
df['DAYS_EMPLOYED'].replace(365243, np.nan, inplace= True)

In [49]:
df['DAYS_EMPLOYED'].head(15)

0     -637.0
1    -1188.0
2     -225.0
3    -3039.0
4    -3038.0
5    -1588.0
6    -3130.0
7     -449.0
8        NaN
9    -2019.0
10    -679.0
11       NaN
12   -2717.0
13   -3028.0
14    -203.0
Name: DAYS_EMPLOYED, dtype: float64

In [50]:
 inc_by_org = df[['AMT_INCOME_TOTAL', 'ORGANIZATION_TYPE']].groupby('ORGANIZATION_TYPE').median()['AMT_INCOME_TOTAL']

In [51]:
inc_by_org

ORGANIZATION_TYPE
Advertising               165600.0
Agriculture               126000.0
Bank                      157500.0
Business Entity Type 1    157500.0
Business Entity Type 2    157500.0
Business Entity Type 3    157500.0
Cleaning                  135000.0
Construction              180000.0
Culture                   157500.0
Electricity               157500.0
Emergency                 162000.0
Government                135000.0
Hotel                     135000.0
Housing                   135000.0
Industry: type 1          157500.0
Industry: type 10         180000.0
Industry: type 11         137227.5
Industry: type 12         157500.0
Industry: type 13         135000.0
Industry: type 2          157500.0
Industry: type 3          135000.0
Industry: type 4          157500.0
Industry: type 5          157500.0
Industry: type 6          139050.0
Industry: type 7          144000.0
Industry: type 8          162450.0
Industry: type 9          180000.0
Insurance                 157500.0
Kindergarten              126000.0
Legal Services            225000.0
Medicine                  135000.0
Military                  202500.0
Mobile                    157500.0
Other                     157500.0
Police                    189000.0
Postal                    112500.0
Realtor                   202500.0
Religion                  162000.0
Restaurant                135000.0
School                    135000.0
Security                  153000.0
Security Ministries       180000.0
Self-employed             148500.0
Services                  157500.0
Telecom                   157500.0
Trade: type 1             135000.0
Trade: type 2             157500.0
Trade: type 3             135000.0
Trade: type 4             176625.0
Trade: type 5             157500.0
Trade: type 6             157500.0
Trade: type 7             144000.0
Transport: type 1         157500.0
Transport: type 2         157500.0
Transport: type 3         157500.0
Transport: type 4         180000.0
University                162000.0
XNA                       117000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [52]:
df['NEW_CREDIT_TO_ANNUITY_RATIO'] = df['AMT_CREDIT'] / df['AMT_ANNUITY']
df[['NEW_CREDIT_TO_ANNUITY_RATIO']].head(10)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,NEW_CREDIT_TO_ANNUITY_RATIO
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,16.461104
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,36.234085
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,20.000000
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,10.532818
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,23.461618
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,17.824857
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0,37.789061
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,36.363636
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,30.142344
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,20.000000
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,30.811730
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,13.893805
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,13.749044
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,31.707938
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,23.603652
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,14.869643
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,19.488040
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,20.000000
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,20.000000
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,31.001281
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,20.000000
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0,30.152510
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,15.298187
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,10.056604
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,19.482820
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,20.316944
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0,36.193452
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,13.724646
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,13.711477
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,20.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,14.868214
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,14.314374
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,15.005461
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,15.302590
307485,456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,20.000000
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,19.445730
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0,34.058050
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0,10.111223
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0,22.576496
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,14.756517
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0,34.204140
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,36.254402
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0,25.127433
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0,10.237203
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,34.014764
307496,456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,20.000000
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0,22.457164
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,25.151384
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0,17.724211
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0,36.235118
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,22.706596
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,21.186441
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0,19.442897
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,20.620632
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0,10.204082
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,9.242325
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,22.459693
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0,22.604623
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,18.317595
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0,13.742556

In [53]:
df['NEW_CREDIT_TO_GOODS_RATIO'] = df['AMT_CREDIT'] / df['AMT_GOODS_PRICE']
df[['NEW_CREDIT_TO_GOODS_RATIO']].head(10)

0    1.158397
1    1.145199
2    1.000000
3    1.052803
4    1.000000
5    1.079198
6    1.118800
7    1.000000
8    1.116158
9    1.000000
Name: NEW_CREDIT_TO_GOODS_RATIO, dtype: float64

In [59]:
df['NEW_DOC_IND_AVG'] = df[docs].mean(axis=1)
df[['NEW_DOC_IND_AVG']].head(10)

        NEW_DOC_IND_AVG
0                  0.05
1                  0.05
2                  0.00
3                  0.05
4                  0.05
5                  0.05
6                  0.10
7                  0.05
8                  0.05
9                  0.00
10                 0.05
11                 0.05
12                 0.05
13                 0.05
14                 0.05
15                 0.05
16                 0.05
17                 0.00
18                 0.05
19                 0.05
20                 0.00
21                 0.05
22                 0.05
23                 0.05
24                 0.05
25                 0.05
26                 0.10
27                 0.05
28                 0.05
29                 0.00
...                 ...
307481             0.05
307482             0.05
307483             0.05
307484             0.05
307485             0.00
307486             0.05
307487             0.05
307488             0.05
307489             0.05
307490             0.05
307491             0.05
307492             0.05
307493             0.05
307494             0.05
307495             0.05
307496             0.00
307497             0.05
307498             0.05
307499             0.05
307500             0.05
307501             0.05
307502             0.05
307503             0.05
307504             0.05
307505             0.05
307506             0.05
307507             0.05
307508             0.05
307509             0.05
307510             0.05

[307507 rows x 1 columns]

In [60]:
df['NEW_DOC_IND_STD'] = df[docs].std(axis=1)
df[['NEW_DOC_IND_STD']].head(10)

   NEW_DOC_IND_STD
0         0.223607
1         0.223607
2         0.000000
3         0.223607
4         0.223607
5         0.223607
6         0.307794
7         0.223607
8         0.223607
9         0.000000

In [62]:
df['NEW_LIVE_IND_SUM'] = df[live].sum(axis=1)
df[['NEW_LIVE_IND_SUM']].head(10)

   NEW_LIVE_IND_SUM
0                 4
1                 4
2                 5
3                 3
4                 3
5                 5
6                 4
7                 4
8                 2
9                 3

In [61]:
df['NEW_DOC_IND_KURT'] = df[docs].kurtosis(axis=1)
df[['NEW_DOC_IND_KURT']].head(10)

   NEW_DOC_IND_KURT
0         20.000000
1         20.000000
2          0.000000
3         20.000000
4         20.000000
5         20.000000
6          7.037037
7         20.000000
8         20.000000
9          0.000000

In [63]:
df['NEW_LIVE_IND_SUM'] = df[live].sum(axis=1)
df[['NEW_LIVE_IND_SUM']].head(10)

   NEW_LIVE_IND_SUM
0                 4
1                 4
2                 5
3                 3
4                 3
5                 5
6                 4
7                 4
8                 2
9                 3

In [64]:
df['NEW_LIVE_IND_STD'] = df[live].std(axis=1)
df[['NEW_LIVE_IND_STD']].head(10)

   NEW_LIVE_IND_STD
0          0.516398
1          0.516398
2          0.408248
3          0.547723
4          0.547723
5          0.408248
6          0.516398
7          0.516398
8          0.516398
9          0.547723

In [65]:
df['NEW_LIVE_IND_KURT'] = df[live].kurtosis(axis=1)
df[['NEW_LIVE_IND_KURT']].head(10)

   NEW_LIVE_IND_KURT
0          -1.875000
1          -1.875000
2           6.000000
3          -3.333333
4          -3.333333
5           6.000000
6          -1.875000
7          -1.875000
8          -1.875000
9          -3.333333

In [66]:
df['NEW_INC_PER_CHLD'] = df['AMT_INCOME_TOTAL'] / (1 + df['CNT_CHILDREN'])
df[['NEW_INC_PER_CHLD']].head(10)

   NEW_INC_PER_CHLD
0          202500.0
1          270000.0
2           67500.0
3          135000.0
4          121500.0
5           99000.0
6           85500.0
7          360000.0
8          112500.0
9          135000.0

In [67]:
df['NEW_INC_BY_ORG'] = df['ORGANIZATION_TYPE'].map(inc_by_org)
df[['NEW_INC_BY_ORG']].head(20)

    NEW_INC_BY_ORG
0         157500.0
1         135000.0
2         135000.0
3         157500.0
4         162000.0
5         157500.0
6         157500.0
7         157500.0
8         117000.0
9         157500.0
10        135000.0
11        117000.0
12        157500.0
13        148500.0
14        157500.0
15        157500.0
16        135000.0
17        180000.0
18        135000.0
19        126000.0

In [69]:
df['NEW_EMPLOY_TO_BIRTH_RATIO'] = df['DAYS_EMPLOYED'] / df['DAYS_BIRTH']
df['NEW_EMPLOY_TO_BIRTH_RATIO']

0         0.067329
1         0.070862
2         0.011814
3         0.159905
4         0.152418
5         0.093737
6         0.227174
7         0.023820
8              NaN
9         0.139540
10        0.066588
11             NaN
12        0.202173
13        0.214965
14        0.013920
15        0.132562
16        0.101848
17        0.019538
18        0.440456
19        0.179591
20        0.234824
21        0.111509
22        0.386327
23             NaN
24        0.066100
25        0.180718
26        0.140355
27        0.077376
28        0.179708
29        0.097669
            ...
307481    0.152441
307482    0.016022
307483         NaN
307484    0.025531
307485    0.055959
307486    0.074016
307487         NaN
307488    0.120690
307489    0.017364
307490    0.195260
307491    0.177934
307492    0.077176
307493    0.131523
307494    0.439430
307495    0.355511
307496    0.125569
307497    0.073266
307498    0.193121
307499    0.511773
307500    0.261206
307501    0.080704
307502    0.543859
307503    0.033614
307504    0.434481
307505         NaN
307506    0.025303
307507         NaN
307508    0.529266
307509    0.400134
307510    0.074869
Name: NEW_EMPLOY_TO_BIRTH_RATIO, Length: 307507, dtype: float64

In [70]:
df['NEW_ANNUITY_TO_INCOME_RATIO'] = df['AMT_ANNUITY'] / (1 + df['AMT_INCOME_TOTAL'])
df[['NEW_ANNUITY_TO_INCOME_RATIO']].head(10)

   NEW_ANNUITY_TO_INCOME_RATIO
0                     0.121977
1                     0.132216
2                     0.099999
3                     0.219898
4                     0.179961
5                     0.277952
6                     0.241525
7                     0.116875
8                     0.300677
9                     0.149999

In [71]:
df['NEW_SOURCES_PROD'] = df['EXT_SOURCE_1'] * df['EXT_SOURCE_2'] * df['EXT_SOURCE_3'] 
df[['NEW_SOURCES_PROD']].head(10)

   NEW_SOURCES_PROD
0          0.003043
1               NaN
2               NaN
3               NaN
4               NaN
5               NaN
6          0.276010
7               NaN
8          0.090840
9               NaN

In [72]:
 df['NEW_EXT_SOURCES_MEAN'] = df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].mean(axis=1)
 df['NEW_EXT_SOURCES_MEAN'].head(10)

0    0.161787
1    0.466757
2    0.642739
3    0.650442
4    0.322738
5    0.487726
6    0.663607
7    0.627467
8    0.514935
9    0.746644
Name: NEW_EXT_SOURCES_MEAN, dtype: float64

In [73]:
df['NEW_SCORES_STD'] = df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].std(axis=1)
df['NEW_SCORES_STD'].head(10)

0    0.092026
1    0.219895
2    0.122792
3         NaN
4         NaN
5    0.188799
6    0.150717
7    0.122771
8    0.280096
9         NaN
Name: NEW_SCORES_STD, dtype: float64

In [74]:
df['NEW_SCORES_STD'] = df['NEW_SCORES_STD'].fillna(df['NEW_SCORES_STD'].mean())
df['NEW_SCORES_STD'].head(10)

In [76]:
df['NEW_CAR_TO_BIRTH_RATIO'] = df['OWN_CAR_AGE'] / df['DAYS_BIRTH']
df['NEW_CAR_TO_BIRTH_RATIO'].head(10)

0         NaN
1         NaN
2   -0.001365
3         NaN
4         NaN
5         NaN
6   -0.001234
7   -0.000424
8         NaN
9         NaN
Name: NEW_CAR_TO_BIRTH_RATIO, dtype: float64

In [77]:
df['NEW_CAR_TO_EMPLOY_RATIO'] = df['OWN_CAR_AGE'] / df['DAYS_EMPLOYED']
df['NEW_CAR_TO_EMPLOY_RATIO'].head(10)

0         NaN
1         NaN
2   -0.115556
3         NaN
4         NaN
5         NaN
6   -0.005431
7   -0.017817
8         NaN
9         NaN
Name: NEW_CAR_TO_EMPLOY_RATIO, dtype: float64

In [78]:
df['NEW_PHONE_TO_BIRTH_RATIO'] = df['DAYS_LAST_PHONE_CHANGE'] / df['DAYS_BIRTH']
df['NEW_PHONE_TO_BIRTH_RATIO'].head(10)

0    0.119860
1    0.049389
2    0.042791
3    0.032465
4    0.055489
5    0.149696
6    0.113369
7    0.056764
8   -0.000000
9    0.115627
Name: NEW_PHONE_TO_BIRTH_RATIO, dtype: float64

In [79]:
df['NEW_PHONE_TO_EMPLOY_RATIO'] = df['DAYS_LAST_PHONE_CHANGE'] / df['DAYS_EMPLOYED']
df['NEW_PHONE_TO_EMPLOY_RATIO'].head(10)

0    1.780220
1    0.696970
2    3.622222
3    0.203027
4    0.364055
5    1.596977
6    0.499042
7    2.383073
8         NaN
9    0.828628
Name: NEW_PHONE_TO_EMPLOY_RATIO, dtype: float64

In [80]:
df['NEW_CREDIT_TO_INCOME_RATIO'] = df['AMT_CREDIT'] / df['AMT_INCOME_TOTAL']
df['NEW_CREDIT_TO_INCOME_RATIO'].head(10)

0    2.007889
1    4.790750
2    2.000000
3    2.316167
4    4.222222
5    4.954500
6    9.127053
7    4.250000
8    9.063200
9    3.000000
Name: NEW_CREDIT_TO_INCOME_RATIO, dtype: float64

In [82]:
# Categorical features with Binary encode (0 or 1; two categories)
for bin_feature in ['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY']:
    df[bin_feature], uniques = pd.factorize(df[bin_feature])

In [86]:
df[bin_feature], uniques

(0         0
 1         1
 2         0
 3         0
 4         0
 5         0
 6         0
 7         0
 8         0
 9         0
 10        0
 11        0
 12        0
 13        1
 14        0
 15        0
 16        1
 17        0
 18        0
 19        0
 20        0
 21        0
 22        1
 23        0
 24        1
 25        0
 26        0
 27        0
 28        0
 29        0
          ..
 307481    0
 307482    0
 307483    0
 307484    1
 307485    0
 307486    0
 307487    0
 307488    1
 307489    0
 307490    0
 307491    0
 307492    0
 307493    0
 307494    1
 307495    1
 307496    1
 307497    0
 307498    0
 307499    0
 307500    0
 307501    0
 307502    0
 307503    0
 307504    0
 307505    0
 307506    1
 307507    0
 307508    0
 307509    0
 307510    1
 Name: FLAG_OWN_REALTY, Length: 307507, dtype: int64,
 Index(['Y', 'N'], dtype='object'))

In [88]:
# Categorical features with One-Hot encode
df, cat_cols = one_hot_encoder(df, False)

In [91]:
len(cat_cols)

133

# Preprocess POS_CASH_balance.csv

In [64]:
pos = pd.read_csv('../input/POS_CASH_balance.csv', nrows = None)
pos, cat_cols = one_hot_encoder(pos, nan_as_category= True)

In [ ]:
cat_cols

### Features

In [65]:
aggregations = {
        'MONTHS_BALANCE': ['max', 'mean', 'size'],
        'SK_DPD': ['max', 'mean'],
        'SK_DPD_DEF': ['max', 'mean']
    }

In [68]:
for cat in cat_cols:
        aggregations[cat] = ['mean']

In [70]:
aggregations

{'MONTHS_BALANCE': ['max', 'mean', 'size'],
 'SK_DPD': ['max', 'mean'],
 'SK_DPD_DEF': ['max', 'mean'],
 'NAME_CONTRACT_STATUS_Active': ['mean'],
 'NAME_CONTRACT_STATUS_Amortized debt': ['mean'],
 'NAME_CONTRACT_STATUS_Approved': ['mean'],
 'NAME_CONTRACT_STATUS_Canceled': ['mean'],
 'NAME_CONTRACT_STATUS_Completed': ['mean'],
 'NAME_CONTRACT_STATUS_Demand': ['mean'],
 'NAME_CONTRACT_STATUS_Returned to the store': ['mean'],
 'NAME_CONTRACT_STATUS_Signed': ['mean'],
 'NAME_CONTRACT_STATUS_XNA': ['mean'],
 'NAME_CONTRACT_STATUS_nan': ['mean']}

In [71]:
pos_agg = pos.groupby('SK_ID_CURR').agg(aggregations)
pos_agg.columns = pd.Index(['POS_' + e[0] + "_" + e[1].upper() for e in pos_agg.columns.tolist()])

In [72]:
pos_agg

,POS_MONTHS_BALANCE_MAX,POS_MONTHS_BALANCE_MEAN,POS_MONTHS_BALANCE_SIZE,POS_SK_DPD_MAX,POS_SK_DPD_MEAN,POS_SK_DPD_DEF_MAX,POS_SK_DPD_DEF_MEAN,POS_NAME_CONTRACT_STATUS_Active_MEAN,POS_NAME_CONTRACT_STATUS_Amortized debt_MEAN,POS_NAME_CONTRACT_STATUS_Approved_MEAN,POS_NAME_CONTRACT_STATUS_Canceled_MEAN,POS_NAME_CONTRACT_STATUS_Completed_MEAN,POS_NAME_CONTRACT_STATUS_Demand_MEAN,POS_NAME_CONTRACT_STATUS_Returned to the store_MEAN,POS_NAME_CONTRACT_STATUS_Signed_MEAN,POS_NAME_CONTRACT_STATUS_XNA_MEAN,POS_NAME_CONTRACT_STATUS_nan_MEAN
SK_ID_CURR,,,,,,,,,,,,,,,,,
100001,-53,-72.555556,9,7,0.777778,7,0.777778,0.777778,0.0,0.0,0.0,0.222222,0.0,0.000000,0.000000,0.0,0
100002,-1,-10.000000,19,0,0.000000,0,0.000000,1.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0
100003,-18,-43.785714,28,0,0.000000,0,0.000000,0.928571,0.0,0.0,0.0,0.071429,0.0,0.000000,0.000000,0.0,0
100004,-24,-25.500000,4,0,0.000000,0,0.000000,0.750000,0.0,0.0,0.0,0.250000,0.0,0.000000,0.000000,0.0,0
100005,-15,-20.000000,11,0,0.000000,0,0.000000,0.818182,0.0,0.0,0.0,0.090909,0.0,0.000000,0.090909,0.0,0
100006,-1,-9.619048,21,0,0.000000,0,0.000000,0.857143,0.0,0.0,0.0,0.095238,0.0,0.047619,0.000000,0.0,0
100007,-1,-33.636364,66,0,0.000000,0,0.000000,0.939394,0.0,0.0,0.0,0.045455,0.0,0.000000,0.015152,0.0,0
100008,-2,-43.662651,83,1294,339.060241,0,0.000000,0.939759,0.0,0.0,0.0,0.048193,0.0,0.000000,0.012048,0.0,0
100009,-1,-33.062500,64,0,0.000000,0,0.000000,0.890625,0.0,0.0,0.0,0.109375,0.0,0.000000,0.000000,0.0,0
100010,-25,-30.000000,11,0,0.000000,0,0.000000,0.909091,0.0,0.0,0.0,0.090909,0.0,0.000000,0.000000,0.0,0
100011,-10,-46.400000,75,952,205.666667,9,0.346667,0.973333,0.0,0.0,0.0,0.026667,0.0,0.000000,0.000000,0.0,0
100012,-5,-22.086957,46,0,0.000000,0,0.000000,0.934783,0.0,0.0,0.0,0.065217,0.0,0.000000,0.000000,0.0,0
100013,-3,-29.555556,36,18,0.944444,0,0.000000,0.888889,0.0,0.0,0.0,0.083333,0.0,0.000000,0.027778,0.0,0
100014,-1,-18.250000,16,0,0.000000,0,0.000000,0.937500,0.0,0.0,0.0,0.062500,0.0,0.000000,0.000000,0.0,0
100015,-69,-74.000000,11,13,1.181818,13,1.181818,0.909091,0.0,0.0,0.0,0.090909,0.0,0.000000,0.000000,0.0,0
100016,-18,-48.253731,67,0,0.000000,0,0.000000,0.955224,0.0,0.0,0.0,0.044776,0.0,0.000000,0.000000,0.0,0
100017,-1,-33.387097,31,0,0.000000,0,0.000000,0.967742,0.0,0.0,0.0,0.032258,0.0,0.000000,0.000000,0.0,0
100018,-2,-33.880000,25,0,0.000000,0,0.000000,0.920000,0.0,0.0,0.0,0.080000,0.0,0.000000,0.000000,0.0,0
100019,-24,-27.500000,8,0,0.000000,0,0.000000,0.875000,0.0,0.0,0.0,0.125000,0.0,0.000000,0.000000,0.0,0
100020,-2,-9.000000,14,0,0.000000,0,0.000000,0.928571,0.0,0.0,0.0,0.071429,0.0,0.000000,0.000000,0.0,0
100021,-2,-37.074074,27,0,0.000000,0,0.000000,0.888889,0.0,0.0,0.0,0.111111,0.0,0.000000,0.000000,0.0,0
100022,-2,-5.000000,7,0,0.000000,0,0.000000,1.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0
100023,-5,-52.724138,29,0,0.000000,0,0.000000,0.896552,0.0,0.0,0.0,0.103448,0.0,0.000000,0.000000,0.0,0
100025,-22,-42.850000,40,0,0.000000,0,0.000000,0.925000,0.0,0.0,0.0,0.075000,0.0,0.000000,0.000000,0.0,0
100026,-12,-32.909091,11,0,0.000000,0,0.000000,0.818182,0.0,0.0,0.0,0.181818,0.0,0.000000,0.000000,0.0,0
100027,-4,-15.000000,23,0,0.000000,0,0.000000,0.956522,0.0,0.0,0.0,0.043478,0.0,0.000000,0.000000,0.0,0
100028,-20,-41.967742,31,0,0.000000,0,0.000000,0.935484,0.0,0.0,0.0,0.064516,0.0,0.000000,0.000000,0.0,0
100029,-6,-8.500000,6,0,0.000000,0,0.000000,0.833333,0.0,0.0,0.0,0.166667,0.0,0.000000,0.000000,0.0,0
100030,-7,-55.214286,14,0,0.000000,0,0.000000,0.857143,0.0,0.0,0.0,0.142857,0.0,0.000000,0.000000,0.0,0
100032,-43,-46.000000,7,0,0.000000,0,0.000000,0.857143,0.0,0.0,0.0,0.142857,0.0,0.000000,0.000000,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456225,-1,-19.421053,57,0,0.000000,0,0.000000,0.964912,0.0,0.0,0.0,0.035088,0.0,0.000000,0.000000,0.0,0
456226,-16,-18.000000,5,0,0.000000,0,0.000000,0.000000,0.0,0.0,0.0,0.200000,0.0,0.000000,0.800000,0.0,0
456227,-4,-45.600000,55,0,0.000000,0,0.000000,0.890909,0.0,0.0,0.0,0.090909,0.0,0.000000,0.018182,0.0,0
456228,-9,-51.054054,74,0,0.000000,0,0.000000,0.905405,0.0,0.0,0.0,0.067568,0.0,0.000000,0.027027,0.0,0
456230,-1,-40.961538,26,0,0.000000,0,0.000000,0.923077,0.0,0.0,0.0,0.076923,0.0,0.000000,0.000000,0.0,0
456231,-9,-17.517241,29,0,0.000000,0,0.000000,0.827586,0.0,0.0,0.0,0.172414,0.0,0.000000,0.000000,0.0,0
456232,-2,-11.535714,28,0,0.000000,0,0.000000,0.892857,0.0,0.0,0.0,0.071429,0.0,0.000000,0.035714,0.0,0
456233,-1,-5.500000,10,0,0.000000,0,0.000000,1.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0
456234,-28,-43.642857,14,16,1.142857,16,1.142857,0.857143,0.0,0.0,0.0,0.142857,0.0,0.000000,0.000000,0.0,0
456235,-2,-16.200000,35,0,0.000000,0,0.000000,0.971429,0.0,0.0,0.0,0.028571,0.0,0.000000,0.000000,0.0,0
456236,-43,-62.666667,36,0,0.000000,0,0.000000,0.888889,0.0,0.0,0.0,0.083333,0.0,0.000000,0.027778,0.0,0
456237,-1,-19.785714,42,0,0.000000,0,0.000000,0.928571,0.0,0.0,0.0,0.071429,0.0,0.000000,0.000000,0.0,0
456238,-7,-9.500000,6,0,0.000000,0,0.000000,0.666667,0.0,0.0,0.0,0.166667,0.0,0.000000,0.166667,0.0,0
456239,-86,-91.000000,11,0,0.000000,0,0.000000,0.909091,0.0,0.0,0.0,0.090909,0.0,0.000000,0.000000,0.0,0
456240,-1,-13.396226,53,0,0.000000,0,0.000000,0.962264,0.0,0.0,0.0,0.037736,0.0,0.000000,0.000000,0.0,0
456241,-2,-23.651163,43,0,0.000000,0,0.000000,0.930233,0.0,0.0,0.0,0.046512,0.0,0.000000,0.023256,0.0,0
456242,-1,-13.250000,32,0,0.000000,0,0.000000,0.937500,0.0,0.0,0.0,0.062500,0.0,0.000000,0.000000,0.0,0
456243,-2,-25.818182,22,0,0.000000,0,0.000000,0.863636,0.0,0.0,0.0,0.136364,0.0,0.000000,0.000000,0.0,0
456244,-1,-38.412500,80,4,0.087500,4,0.087500,0.900000,0.0,0.0,0.0,0.100000,0.0,0.000000,0.000000,0.0,0
456245,-1,-7.250000,20,0,0.000000,0,0.000000,0.950000,0.0,0.0,0.0,0.050000,0.0,0.000000,0.000000,0.0,0
456246,-44,-47.000000,7,0,0.000000,0,0.000000,0.857143,0.0,0.0,0.0,0.142857,0.0,0.000000,0.000000,0.0,0
456247,-11,-57.333333,27,0,0.000000,0,0.000000,0.888889,0.0,0.0,0.0,0.111111,0.0,0.000000,0.000000,0.0,0
456248,-2,-30.162791,43,20,1.767442,0,0.000000,0.953488,0.0,0.0,0.0,0.046512,0.0,0.000000,0.000000,0.0,0
456249,-38,-44.000000,13,0,0.000000,0,0.000000,0.923077,0.0,0.0,0.0,0.076923,0.0,0.000000,0.000000,0.0,0
456250,-1,-17.100000,30,0,0.000000,0,0.000000,0.933333,0.0,0.0,0.0,0.066667,0.0,0.000000,0.000000,0.0,0
456251,-1,-5.000000,9,0,0.000000,0,0.000000,0.777778,0.0,0.0,0.0,0.111111,0.0,0.000000,0.111111,0.0,0
456252,-76,-79.000000,7,0,0.000000,0,0.000000,0.857143,0.0,0.0,0.0,0.142857,0.0,0.000000,0.000000,0.0,0
456253,-57,-79.235294,17,5,0.294118,5,0.294118,0.882353,0.0,0.0,0.0,0.117647,0.0,0.000000,0.000000,0.0,0
456254,-1,-5.550000,20,0,0.000000,0,0.000000,1.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0
456255,-2,-16.408451,71,5,0.070423,5,0.070423,0.915493,0.0,0.0,0.0,0.084507,0.0,0.000000,0.000000,0.0,0

### Count pos cash accounts

In [73]:
pos_agg['POS_COUNT'] = pos.groupby('SK_ID_CURR').size()

In [75]:
pos_agg['POS_COUNT']

SK_ID_CURR
100001     9
100002    19
100003    28
100004     4
100005    11
100006    21
100007    66
100008    83
100009    64
100010    11
100011    75
100012    46
100013    36
100014    16
100015    11
100016    67
100017    31
100018    25
100019     8
100020    14
100021    27
100022     7
100023    29
100025    40
100026    11
100027    23
100028    31
100029     6
100030    14
100032     7
          ..
456225    57
456226     5
456227    55
456228    74
456230    26
456231    29
456232    28
456233    10
456234    14
456235    35
456236    36
456237    42
456238     6
456239    11
456240    53
456241    43
456242    32
456243    22
456244    80
456245    20
456246     7
456247    27
456248    43
456249    13
456250    30
456251     9
456252     7
456253    17
456254    20
456255    71
Name: POS_COUNT, Length: 337252, dtype: int64

In [76]:
del pos

In [77]:
gc.collect()

44

# Preprocess installments_payments.csv

In [5]:
ins = pd.read_csv('../input/installments_payments.csv', nrows = None)

In [19]:
ins, cat_cols = one_hot_encoder(ins, nan_as_category= True)

In [20]:
cat_cols

[]

### Percentage and difference paid in each installment (amount paid and installment value)

In [7]:
ins['PAYMENT_PERC'] = ins['AMT_PAYMENT'] / ins['AMT_INSTALMENT']

In [8]:
ins['PAYMENT_PERC']

0           1.000000
1           1.000000
2           1.000000
3           1.000000
4           0.997942
5           1.000000
6           1.000000
7           1.000000
8           1.000000
9           1.000000
10          1.000000
11          1.000000
12          1.000000
13          1.000000
14          1.000000
15          1.000000
16          1.000000
17          0.999712
18          1.000000
19          1.000000
20          1.000000
21          1.000000
22          1.000000
23          1.000000
24          1.000000
25          1.000000
26          1.000000
27          1.000000
28          1.000000
29          1.000000
              ...
13605371         NaN
13605372         NaN
13605373         NaN
13605374         NaN
13605375         NaN
13605376         NaN
13605377         NaN
13605378         NaN
13605379         NaN
13605380         NaN
13605381         NaN
13605382         NaN
13605383         NaN
13605384         NaN
13605385         NaN
13605386         NaN
13605387         NaN
13605388         NaN
13605389         NaN
13605390         NaN
13605391         NaN
13605392         NaN
13605393         NaN
13605394         NaN
13605395         NaN
13605396         NaN
13605397         NaN
13605398         NaN
13605399         NaN
13605400         NaN
Name: PAYMENT_PERC, Length: 13605401, dtype: float64

In [9]:
ins['PAYMENT_DIFF'] = ins['AMT_INSTALMENT'] - ins['AMT_PAYMENT']

In [10]:
ins['PAYMENT_DIFF']

0           0.000
1           0.000
2           0.000
3           0.000
4           4.455
5           0.000
6           0.000
7           0.000
8           0.000
9           0.000
10          0.000
11          0.000
12          0.000
13          0.000
14          0.000
15          0.000
16          0.000
17          3.600
18          0.000
19          0.000
20          0.000
21          0.000
22          0.000
23          0.000
24          0.000
25          0.000
26          0.000
27          0.000
28          0.000
29          0.000
            ...
13605371      NaN
13605372      NaN
13605373      NaN
13605374      NaN
13605375      NaN
13605376      NaN
13605377      NaN
13605378      NaN
13605379      NaN
13605380      NaN
13605381      NaN
13605382      NaN
13605383      NaN
13605384      NaN
13605385      NaN
13605386      NaN
13605387      NaN
13605388      NaN
13605389      NaN
13605390      NaN
13605391      NaN
13605392      NaN
13605393      NaN
13605394      NaN
13605395      NaN
13605396      NaN
13605397      NaN
13605398      NaN
13605399      NaN
13605400      NaN
Name: PAYMENT_DIFF, Length: 13605401, dtype: float64

## # Days past due and days before due (no negative values)

In [11]:
ins['DPD'] = ins['DAYS_ENTRY_PAYMENT'] - ins['DAYS_INSTALMENT']
ins['DPD']

0           -7.0
1            0.0
2            0.0
3           -8.0
4           17.0
5          -33.0
6           -3.0
7          -26.0
8            0.0
9          -39.0
10          -4.0
11          -7.0
12           0.0
13         -45.0
14           0.0
15           0.0
16          -3.0
17         -11.0
18         -13.0
19           6.0
20          -4.0
21          -3.0
22          -5.0
23           0.0
24          -5.0
25         -15.0
26         -11.0
27         -13.0
28           0.0
29          -1.0
            ...
13605371     NaN
13605372     NaN
13605373     NaN
13605374     NaN
13605375     NaN
13605376     NaN
13605377     NaN
13605378     NaN
13605379     NaN
13605380     NaN
13605381     NaN
13605382     NaN
13605383     NaN
13605384     NaN
13605385     NaN
13605386     NaN
13605387     NaN
13605388     NaN
13605389     NaN
13605390     NaN
13605391     NaN
13605392     NaN
13605393     NaN
13605394     NaN
13605395     NaN
13605396     NaN
13605397     NaN
13605398     NaN
13605399     NaN
13605400     NaN
Name: DPD, Length: 13605401, dtype: float64

In [12]:
ins['DBD'] = ins['DAYS_INSTALMENT'] - ins['DAYS_ENTRY_PAYMENT']
ins['DBD']

0            7.0
1            0.0
2            0.0
3            8.0
4          -17.0
5           33.0
6            3.0
7           26.0
8            0.0
9           39.0
10           4.0
11           7.0
12           0.0
13          45.0
14           0.0
15           0.0
16           3.0
17          11.0
18          13.0
19          -6.0
20           4.0
21           3.0
22           5.0
23           0.0
24           5.0
25          15.0
26          11.0
27          13.0
28           0.0
29           1.0
            ...
13605371     NaN
13605372     NaN
13605373     NaN
13605374     NaN
13605375     NaN
13605376     NaN
13605377     NaN
13605378     NaN
13605379     NaN
13605380     NaN
13605381     NaN
13605382     NaN
13605383     NaN
13605384     NaN
13605385     NaN
13605386     NaN
13605387     NaN
13605388     NaN
13605389     NaN
13605390     NaN
13605391     NaN
13605392     NaN
13605393     NaN
13605394     NaN
13605395     NaN
13605396     NaN
13605397     NaN
13605398     NaN
13605399     NaN
13605400     NaN
Name: DBD, Length: 13605401, dtype: float64

In [13]:
ins['DPD'] = ins['DPD'].apply(lambda x: x if x > 0 else 0)
ins['DPD']

0            0.0
1            0.0
2            0.0
3            0.0
4           17.0
5            0.0
6            0.0
7            0.0
8            0.0
9            0.0
10           0.0
11           0.0
12           0.0
13           0.0
14           0.0
15           0.0
16           0.0
17           0.0
18           0.0
19           6.0
20           0.0
21           0.0
22           0.0
23           0.0
24           0.0
25           0.0
26           0.0
27           0.0
28           0.0
29           0.0
            ...
13605371     0.0
13605372     0.0
13605373     0.0
13605374     0.0
13605375     0.0
13605376     0.0
13605377     0.0
13605378     0.0
13605379     0.0
13605380     0.0
13605381     0.0
13605382     0.0
13605383     0.0
13605384     0.0
13605385     0.0
13605386     0.0
13605387     0.0
13605388     0.0
13605389     0.0
13605390     0.0
13605391     0.0
13605392     0.0
13605393     0.0
13605394     0.0
13605395     0.0
13605396     0.0
13605397     0.0
13605398     0.0
13605399     0.0
13605400     0.0
Name: DPD, Length: 13605401, dtype: float64

In [14]:
ins['DBD'] = ins['DBD'].apply(lambda x: x if x > 0 else 0)
ins['DBD']

0            7.0
1            0.0
2            0.0
3            8.0
4            0.0
5           33.0
6            3.0
7           26.0
8            0.0
9           39.0
10           4.0
11           7.0
12           0.0
13          45.0
14           0.0
15           0.0
16           3.0
17          11.0
18          13.0
19           0.0
20           4.0
21           3.0
22           5.0
23           0.0
24           5.0
25          15.0
26          11.0
27          13.0
28           0.0
29           1.0
            ...
13605371     0.0
13605372     0.0
13605373     0.0
13605374     0.0
13605375     0.0
13605376     0.0
13605377     0.0
13605378     0.0
13605379     0.0
13605380     0.0
13605381     0.0
13605382     0.0
13605383     0.0
13605384     0.0
13605385     0.0
13605386     0.0
13605387     0.0
13605388     0.0
13605389     0.0
13605390     0.0
13605391     0.0
13605392     0.0
13605393     0.0
13605394     0.0
13605395     0.0
13605396     0.0
13605397     0.0
13605398     0.0
13605399     0.0
13605400     0.0
Name: DBD, Length: 13605401, dtype: float64

### Features: Perform aggregations

In [15]:
aggregations = {
        'NUM_INSTALMENT_VERSION': ['nunique'],
        'DPD': ['max', 'mean', 'sum'],
        'DBD': ['max', 'mean', 'sum'],
        'PAYMENT_PERC': ['max', 'mean', 'sum', 'var'],
        'PAYMENT_DIFF': ['max', 'mean', 'sum', 'var'],
        'AMT_INSTALMENT': ['max', 'mean', 'sum'],
        'AMT_PAYMENT': ['min', 'max', 'mean', 'sum'],
        'DAYS_ENTRY_PAYMENT': ['max', 'mean', 'sum']
    }

In [16]:
for cat in cat_cols:
        aggregations[cat] = ['mean']

In [17]:
aggregations

{'NUM_INSTALMENT_VERSION': ['nunique'],
 'DPD': ['max', 'mean', 'sum'],
 'DBD': ['max', 'mean', 'sum'],
 'PAYMENT_PERC': ['max', 'mean', 'sum', 'var'],
 'PAYMENT_DIFF': ['max', 'mean', 'sum', 'var'],
 'AMT_INSTALMENT': ['max', 'mean', 'sum'],
 'AMT_PAYMENT': ['min', 'max', 'mean', 'sum'],
 'DAYS_ENTRY_PAYMENT': ['max', 'mean', 'sum']}

In [21]:
ins_agg = ins.groupby('SK_ID_CURR').agg(aggregations)

In [22]:
ins_agg.columns = pd.Index(['INSTAL_' + e[0] + "_" + e[1].upper() for e in ins_agg.columns.tolist()])

In [23]:
ins_agg

,INSTAL_NUM_INSTALMENT_VERSION_NUNIQUE,INSTAL_DPD_MAX,INSTAL_DPD_MEAN,INSTAL_DPD_SUM,INSTAL_DBD_MAX,INSTAL_DBD_MEAN,INSTAL_DBD_SUM,INSTAL_PAYMENT_PERC_MAX,INSTAL_PAYMENT_PERC_MEAN,INSTAL_PAYMENT_PERC_SUM,...,INSTAL_AMT_INSTALMENT_MAX,INSTAL_AMT_INSTALMENT_MEAN,INSTAL_AMT_INSTALMENT_SUM,INSTAL_AMT_PAYMENT_MIN,INSTAL_AMT_PAYMENT_MAX,INSTAL_AMT_PAYMENT_MEAN,INSTAL_AMT_PAYMENT_SUM,INSTAL_DAYS_ENTRY_PAYMENT_MAX,INSTAL_DAYS_ENTRY_PAYMENT_MEAN,INSTAL_DAYS_ENTRY_PAYMENT_SUM
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
100001,2,11.0,1.571429,11.0,36.0,8.857143,62.0,1.000000,1.000000,7.000000,...,17397.900,5885.132143,41195.925,3951.000,17397.900,5885.132143,41195.925,-1628.0,-2195.000000,-15365.0
100002,2,0.0,0.000000,0.0,31.0,20.421053,388.0,1.000000,1.000000,19.000000,...,53093.745,11559.247105,219625.695,9251.775,53093.745,11559.247105,219625.695,-49.0,-315.421053,-5993.0
100003,2,0.0,0.000000,0.0,14.0,7.160000,179.0,1.000000,1.000000,25.000000,...,560835.360,64754.586000,1618864.650,6662.970,560835.360,64754.586000,1618864.650,-544.0,-1385.320000,-34633.0
100004,2,0.0,0.000000,0.0,11.0,7.666667,23.0,1.000000,1.000000,3.000000,...,10573.965,7096.155000,21288.465,5357.250,10573.965,7096.155000,21288.465,-727.0,-761.666667,-2285.0
100005,2,1.0,0.111111,1.0,37.0,23.666667,213.0,1.000000,1.000000,9.000000,...,17656.245,6240.205000,56161.845,4813.200,17656.245,6240.205000,56161.845,-470.0,-609.555556,-5486.0
100006,2,0.0,0.000000,0.0,77.0,19.375000,310.0,1.000000,1.000000,16.000000,...,691786.890,62947.088438,1007153.415,2482.920,691786.890,62947.088438,1007153.415,-12.0,-271.625000,-4346.0
100007,2,12.0,0.954545,63.0,31.0,4.590909,303.0,1.000000,0.954545,63.000000,...,22678.785,12666.444545,835985.340,0.180,22678.785,12214.060227,806127.975,-14.0,-1032.242424,-68128.0
100008,2,1317.0,37.628571,1317.0,28.0,11.514286,403.0,1.000000,0.971429,34.000000,...,432218.295,27702.964286,969603.750,227.160,432218.295,27360.502714,957617.595,-82.0,-1237.800000,-43323.0
100009,1,7.0,0.137255,7.0,23.0,8.725490,445.0,1.000000,1.000000,51.000000,...,17341.605,9568.531765,487995.120,6155.280,17341.605,9568.531765,487995.120,-58.0,-864.411765,-44085.0
100010,1,0.0,0.000000,0.0,30.0,11.900000,119.0,1.000000,1.000000,10.000000,...,27463.410,27449.208000,274492.080,27321.390,27463.410,27449.208000,274492.080,-774.0,-915.900000,-9159.0
100011,2,958.0,7.946154,1033.0,32.0,4.807692,625.0,1.000000,0.907692,118.000000,...,46485.000,13575.715615,1764843.030,449.685,46485.000,11328.893654,1472756.175,-37.0,-1150.923077,-149620.0
100012,4,14.0,0.562500,27.0,90.0,25.875000,1242.0,6.189100,1.049621,50.381812,...,49204.890,9584.503125,460056.150,5.850,58687.245,10451.285625,501661.710,-151.0,-690.312500,-33135.0
100013,3,21.0,0.541935,84.0,38.0,5.722581,887.0,1.000000,0.935484,145.000000,...,357347.745,10897.898516,1689174.270,6.165,357347.745,9740.235774,1509736.545,-14.0,-1358.109677,-210507.0
100014,1,5.0,1.052632,20.0,30.0,9.263158,176.0,1.000000,0.736842,14.000000,...,14045.625,11826.206053,224697.915,530.100,14045.625,8783.197105,166880.745,-36.0,-584.473684,-11105.0
100015,1,21.0,2.100000,21.0,29.0,15.000000,150.0,1.000000,1.000000,10.000000,...,7666.920,7658.680500,76586.805,7584.525,7666.920,7658.680500,76586.805,-2108.0,-2237.900000,-22379.0
100016,2,26.0,3.527027,261.0,16.0,4.905405,363.0,1.000000,0.837838,62.000000,...,102028.140,10739.828919,794747.340,3.960,102028.140,8391.646216,620981.820,-539.0,-1297.581081,-96021.0
100017,1,0.0,0.000000,0.0,24.0,10.866667,326.0,1.000000,1.000000,30.000000,...,16967.295,13508.920500,405267.615,11783.520,16967.295,13508.920500,405267.615,-21.0,-962.533333,-28876.0
100018,2,0.0,0.000000,0.0,21.0,6.875000,165.0,1.000000,1.000000,24.000000,...,94906.035,49114.642500,1178751.420,4109.265,94906.035,49114.642500,1178751.420,-40.0,-1004.208333,-24101.0
100019,3,0.0,0.000000,0.0,66.0,30.500000,244.0,4.218168,1.441113,11.528903,...,33850.665,15090.468750,120723.750,10518.615,44369.280,20636.628750,165093.030,-716.0,-827.000000,-6616.0
100020,1,0.0,0.000000,0.0,18.0,8.615385,112.0,1.000000,1.000000,13.000000,...,8779.770,7136.958462,92780.460,5729.265,8779.770,7136.958462,92780.460,-35.0,-242.692308,-3155.0
100021,2,15.0,2.434783,56.0,46.0,14.739130,339.0,1.000000,1.000000,23.000000,...,52236.180,9059.022391,208357.515,2705.760,52236.180,9059.022391,208357.515,-66.0,-1023.217391,-23534.0
100022,1,0.0,0.000000,0.0,27.0,23.428571,164.0,1.000000,1.000000,7.000000,...,6765.975,6765.975000,47361.825,6765.975,6765.975,6765.975000,47361.825,-51.0,-142.428571,-997.0
100023,2,0.0,0.000000,0.0,43.0,15.653846,407.0,1.000000,1.000000,26.000000,...,231819.525,18982.580192,493547.085,7992.000,231819.525,18982.580192,493547.085,-166.0,-1622.884615,-42195.0
100025,2,14.0,1.565217,72.0,35.0,11.652174,536.0,1.000000,0.804348,37.000000,...,376810.425,36369.358043,1672990.470,2.925,376810.425,31358.615870,1442496.330,-697.0,-1304.326087,-59999.0
100026,2,0.0,0.000000,0.0,17.0,9.375000,75.0,1.000000,1.000000,8.000000,...,770004.315,119294.595000,954356.760,23531.175,770004.315,119294.595000,954356.760,-425.0,-1105.875000,-8847.0
100027,1,0.0,0.000000,0.0,23.0,9.545455,210.0,1.000000,1.000000,22.000000,...,28077.570,24519.289091,539424.360,21553.740,28077.570,24519.289091,539424.360,-116.0,-446.000000,-9812.0
100028,3,7.0,0.265487,30.0,19.0,3.265487,369.0,1.000000,0.911504,103.000000,...,38988.540,4979.282257,562658.895,1.170,38988.540,4356.731549,492310.665,-29.0,-858.548673,-97016.0
100029,2,0.0,0.000000,0.0,23.0,19.750000,79.0,1.000000,1.000000,4.000000,...,66993.345,33917.096250,135668.385,22891.680,66993.345,33917.096250,135668.385,-224.0,-267.750000,-1071.0
100030,2,0.0,0.000000,0.0,35.0,21.833333,131.0,1.000000,1.000000,6.000000,...,17846.145,11820.645000,70923.870,9035.685,17846.145,11820.645000,70923.870,-233.0,-730.666667,-4384.0
100032,1,9.0,1.285714,9.0,86.0,47.142857,330.0,1.000000,0.857143,6.000000,...,7912.305,7910.762143,55375.335,4.275,7910.145,6780.432857,47463.030,-1307.0,-1426.142857,-9983.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456225,9,156.0,6.522843,1285.0,38.0,4.827411,951.0,1.000000,0.883249,174.000000,...,148500.000,11007.808401,2168538.255,0.000,148500.000,9379.002563,1847663.505,-15.0,-1104.604061,-217607.0
456226,2,0.0,0.000000,0.0,36.0,16.250000,65.0,1.000000,1.000000,4.000000,...,464404.770,161446.983750,645787.935,60461.055,464404.770,161446.983750,645787.935,-489.0,-549.250000,-2197.0
456227,3,2.0,0.098039,5.0,32.0,7.941176,405.0,4.284774,1.050769,53.589209,...,57217.185,10833.899118,552528.855,837.000,57217.185,11438.332059,583354.935,-139.0,-1365.960784,-69664.0
456228,2,8.0,0.405405,30.0,37.0,7.648649,566.0,1.000000,0.918919,68.000000,...,904762.080,33618.801892,2487791.340,50.625,904762.080,31976.061081,2366228.520,-286.0,-1589.959459,-117657.0
456230,2,0.0,0.000000,0.0,26.0,13.909091,306.0,1.000000,1.000000,22.000000,...,53109.315,35778.949773,787136.895,2789.235,53109.315,35778.949773,787136.895,-29.0,-1089.000000,-23958.0
456231,2,0.0,0.000000,0.0,89.0,22.695652,522.0,1.000000,1.000000,23.000000,...,532647.045,42132.478696,969047.010,3073.545,532647.045,42132.478696,969047.010,-302.0,-548.173913,-12608.0
456232,2,0.0,0.000000,0.0,41.0,14.520000,363.0,1.000000,1.000000,25.000000,...,14983.605,10326.535200,258163.380,2931.345,14983.605,10326.535200,258163.380,-24.0,-332.640000,-8316.0
456233,2,1.0,0.035714,1.0,59.0,14.607143,409.0,1.000000,1.000000,28.000000,...,22500.000,5974.548750,167287.365,24.300,22500.000,5974.548750,167287.365,-20.0,-133.607143,-3741.0
456234,3,24.0,3.214286,45.0,51.0,12.500000,175.0,1.000000,0.928571,13.000000,...,43923.690,10815.624643,151418.745,212.580,43923.690,10461.757500,146464.605,-854.0,-1259.857143,-17638.0
456235,1,0.0,0.000000,0.0,22.0,11.606061,383.0,1.000000,1.000000,33.000000,...,12308.895,6544.707273,215975.340,4787.550,12308.895,6544.707273,215975.340,-38.0,-422.363636,-13938.0
456236,3,5.0,0.183206,24.0,33.0,3.519084,461.0,1.000000,0.961832,126.000000,...,283385.835,12061.647824,1580075.865,4.140,283385.835,11181.032176,1464715.215,-887.0,-2004.458015,-262584.0
456237,3,4.0,0.089552,6.0,19.0,4.402985,295.0,1.000000,0.985075,66.000000,...,263096.955,20339.423060,1362741.345,26.370,263096.955,20307.139925,1360578.375,-19.0,-445.985075,-29881.0
456238,2,0.0,0.000000,0.0,66.0,44.500000,178.0,1.000000,1.000000,4.000000,...,70911.135,24956.831250,99827.325,9638.730,70911.135,24956.831250,99827.325,-256.0,-323.500000,-1294.0
456239,2,1.0,0.008333,1.0,30.0,4.058333,487.0,1.000000,1.000000,120.000000,...,174649.500,7191.231375,862947.765,134.910,174649.500,7191.231375,862947.765,-102.0,-1626.858333,-195223.0
456240,3,7.0,0.375000,21.0,21.0,6.767857,379.0,2.108870,0.929746,52.065760,...,62382.015,36306.894375,2033186.085,1672.785,62382.015,33571.809643,1880021.340,-12.0,-364.785714,-20428.0
456241,1,3.0,0.097561,4.0,31.0,5.536585,227.0,1.000000,0.975610,40.000000,...,32830.245,16159.259634,662529.645,5594.940,32830.245,15849.571829,649832.445,-20.0,-666.414634,-27323.0
456242,2,4.0,0.076923,4.0,52.0,11.115385,578.0,1.000000,1.000000,52.000000,...,27000.000,11415.696058,593616.195,54.000,27000.000,11415.696058,593616.195,-11.0,-274.980769,-14299.0
456243,2,0.0,0.000000,0.0,64.0,24.947368,474.0,1.000000,1.000000,19.000000,...,18934.155,4299.790263,81696.015,2948.085,18934.155,4299.790263,81696.015,-71.0,-821.736842,-15613.0
456244,3,17.0,0.541353,72.0,126.0,7.563910,1006.0,1.000000,0.939850,125.000000,...,889827.255,42421.814323,5642101.305,3.375,889827.255,40468.778797,5382347.580,-31.0,-1065.233083,-141676.0
456245,1,0.0,0.000000,0.0,57.0,23.263158,442.0,1.000000,1.000000,19.000000,...,6481.755,5983.372895,113684.085,5687.865,6481.755,5983.372895,113684.085,-37.0,-220.631579,-4192.0
456246,2,8.0,0.272727,9.0,22.0,5.484848,181.0,1.000000,1.000000,33.000000,...,14419.710,5218.104545,172197.450,29.340,14419.710,5218.104545,172197.450,-7.0,-373.272727,-12318.0
456247,3,15.0,0.238806,32.0,30.0,4.246269,569.0,1.000000,1.000000,134.000000,...,90990.000,5685.241231,761822.325,43.830,90990.000,5685.241231,761822.325,-34.0,-1606.014925,-215206.0
456248,1,25.0,2.021739,93.0,30.0,7.086957,326.0,1.000000,0.913043,42.000000,...,67725.495,44619.088696,2052478.080,26.640,67725.495,43887.146087,2018808.720,-28.0,-996.891304,-45857.0
456249,1,0.0,0.000000,0.0,10.0,2.500000,30.0,1.000000,1.000000,12.000000,...,22782.465,22771.410000,273256.920,22770.405,22782.465,22771.410000,273256.920,-1168.0,-1332.500000,-15990.0
456250,2,10.0,0.420000,21.0,30.0,8.600000,430.0,1.000000,0.980000,49.000000,...,26474.625,13238.063100,661903.155,1.080,26474.625,13044.983400,652249.170,-33.0,-365.760000,-18288.0
456251,2,0.0,0.000000,0.0,46.0,36.285714,254.0,1.000000,1.000000,7.000000,...,12815.010,7492.924286,52450.470,6605.910,12815.010,7492.924286,52450.470,-38.0,-156.285714,-1094.0
456252,1,3.0,0.500000,3.0,11.0,3.333333,20.0,1.000000,1.000000,6.000000,...,10074.465,10069.867500,60419.205,10046.880,10074.465,10069.867500,60419.205,-2327.0,-2393.833333,-14363.0
456253,1,9.0,0.642857,9.0,51.0,15.142857,212.0,1.000000,0.928571,13.000000,...,5575.185,4399.707857,61595.910,27.270,5575.185,4115.915357,57622.815,-1738.0,-2387.428571,-33424.0
456254,1,0.0,0.000000,0.0,31.0,19.000000,361.0,1.000000,1.000000,19.000000,...,19065.825,10239.832895,194556.825,2296.440,19065.825,10239.832895,194556.825,-18.0,-161.263158,-3064.0
456255,4,7.0,0.702703,52.0,35.0,8.770270,649.0,12.388470,1.033463,76.476278,...,615229.515,41464.713649,3068388.810,34.965,669251.655,47646.215878,3525819.975,-76.0,-472.013514,-34929.0

### Count installments accounts

In [24]:
ins_agg['INSTAL_COUNT'] = ins.groupby('SK_ID_CURR').size()

In [25]:
ins_agg['INSTAL_COUNT']

SK_ID_CURR
100001      7
100002     19
100003     25
100004      3
100005      9
100006     16
100007     66
100008     35
100009     51
100010     10
100011    130
100012     48
100013    155
100014     19
100015     10
100016     74
100017     30
100018     24
100019      8
100020     13
100021     23
100022      7
100023     26
100025     46
100026      8
100027     22
100028    113
100029      4
100030      6
100032      7
         ...
456225    197
456226      4
456227     51
456228     74
456230     22
456231     23
456232     25
456233     28
456234     14
456235     33
456236    131
456237     67
456238      4
456239    120
456240     56
456241     41
456242     52
456243     19
456244    133
456245     19
456246     33
456247    134
456248     46
456249     12
456250     50
456251      7
456252      6
456253     14
456254     19
456255     74
Name: INSTAL_COUNT, Length: 339587, dtype: int64

In [26]:
del ins

In [27]:
gc.collect()

42

# Preprocess credit_card_balance.csv

In [29]:
cc = pd.read_csv('../input/credit_card_balance.csv', nrows = None)
cc, cat_cols = one_hot_encoder(cc, nan_as_category= True)

 ### General aggregations

In [31]:
cc.drop(['SK_ID_PREV'], axis= 1, inplace = True)

In [35]:
cc_agg = cc.groupby('SK_ID_CURR').agg(['min', 'max', 'mean', 'sum', 'var'])
cc_agg

           MONTHS_BALANCE                             AMT_BALANCE              \
                      min max  mean   sum         var         min         max
SK_ID_CURR
100006                 -6  -1  -3.5   -21    3.500000       0.000       0.000
100011                -75  -2 -38.5 -2849  462.500000       0.000  189000.000
100013                -96  -1 -48.5 -4656  776.000000       0.000  161420.220
100021                -18  -2 -10.0  -170   25.500000       0.000       0.000
100023                -11  -4  -7.5   -60    6.000000       0.000       0.000
100028                -49  -1 -25.0 -1225  204.166667       0.000   37335.915
100036                -13  -2  -7.5   -90   13.000000       0.000       0.000
100042                -84  -1 -42.5 -3570  595.000000       0.000   93118.455
100043                -33  -1 -17.0  -561   93.500000       0.000  435861.585
100047                -39  -4 -21.5  -774  111.000000       0.000       0.000
100048                -31  -1 -16.0  -496   82.666667       0.000  212013.000
100049                -14  -2  -8.0  -104   15.166667       0.000  133348.950
100050                 -7  -1  -4.0   -28    4.666667       0.000       0.000
100059                -11  -2  -6.5   -65    9.166667       0.000       0.000
100066                -15  -1  -8.0  -120   20.000000       0.000       0.000
100067                -87  -1 -44.0 -3828  638.000000       0.000   47582.100
100075                 -9  -2  -5.5   -44    6.000000   83920.365  245289.465
100077                 -8  -4  -6.0   -30    2.500000       0.000       0.000
100082                -89  -2 -45.5 -4004  652.666667       0.000  129551.895
100083                -26  -2 -14.0  -350   54.166667       0.000       0.000
100086                -84  -1 -42.5 -3570  595.000000       0.000  118726.065
100090                -28  -1 -14.5  -406   67.666667       0.000       0.000
100100                -94  -1 -47.5 -4465  744.166667       0.000   96182.910
100101                -14  -1  -7.5  -105   17.500000       0.000  491449.095
100107                -11  -1  -6.0   -66   11.000000       0.000  139761.495
100109                -82  -4 -43.0 -3397  526.666667       0.000  180264.060
100110                 -5  -1  -3.0   -15    2.500000       0.000       0.000
100112                -20  -4 -12.0  -204   25.500000       0.000       0.000
100114                 -7  -1  -4.0   -28    4.666667       0.000       0.000
100115                 -2  -2  -2.0    -2         NaN   46570.500   46570.500
...                   ...  ..   ...   ...         ...         ...         ...
456173                -17  -2  -9.5  -152   22.666667       0.000  479031.975
456178                -14  -2  -8.0  -104   15.166667       0.000       0.000
456186                -14  -2  -8.0  -104   15.166667       0.000   92045.340
456188                -88  -3 -45.5 -3913  623.500000       0.000       0.000
456189                -23  -1 -12.0  -276   46.000000   32688.900  171593.235
456195                 -5  -2  -3.5   -14    1.666667       0.000       0.000
456198                -96  -1 -48.5 -4656  776.000000       0.000  191455.110
456199                 -7  -1  -4.0   -28    4.666667       0.000       0.000
456201                 -4  -1  -2.5   -10    1.666667       0.000       0.000
456206                -44  -1 -22.5  -990  165.000000       0.000  382692.195
456210                -22  -2 -12.0  -252   38.500000       0.000       0.000
456211                 -2  -2  -2.0    -2         NaN  136570.500  136570.500
456213                -35  -2 -18.5  -629   99.166667       0.000  483402.780
456214                 -5  -1  -3.0   -15    2.500000       0.000  552591.360
456215                -96  -3 -49.5 -4653  744.166667       0.000  133373.475
456217                -95  -1 -48.0 -4560  760.000000   94498.785  193238.865
456219                -10  -1  -5.5   -55    9.166667       0.000  145749.465
456225                -96  -1 -48.5 -4656  776.000000       0.000  197355.420
456233                -10  -1  -5.5   -55    9.166667       0.000  109270.215
456235                -11  -2  -6.5   -65    9.166667       0.000       0.000
456236                -96  -3 -49.5 -4653  744.166667       0.000  179571.870
456237                -15  -1  -8.0  -120   20.000000       0.000  173740.410
456239                -90  -3 -46.5 -4092  652.666667       0.000  275177.340
456241                -34  -2 -18.0  -594   93.500000       0.000       0.000
456242                 -8  -1  -4.5   -36    6.000000   14593.185  217274.805
456244                -41  -1 -21.0  -861  143.500000       0.000  453627.675
456246                 -9  -2  -5.5   -44    6.000000       0.000   43490.115
456247                -96  -2 -49.0 -4655  760.000000       0.000  190202.130
456248                -24  -2 -13.0  -299   46.000000       0.000       0.000
456250                -12  -1  -6.5   -78   13.000000  153832.725  200208.915

                                                      ...   \
                     mean           sum           var ...
SK_ID_CURR                                            ...
100006           0.000000  0.000000e+00  0.000000e+00 ...
100011       54482.111149  4.031676e+06  4.641321e+09 ...
100013       18159.919219  1.743352e+06  1.869473e+09 ...
100021           0.000000  0.000000e+00  0.000000e+00 ...
100023           0.000000  0.000000e+00  0.000000e+00 ...
100028        8085.058163  3.961679e+05  6.232784e+07 ...
100036           0.000000  0.000000e+00  0.000000e+00 ...
100042       33356.183036  2.801919e+06  1.525076e+09 ...
100043      208572.600000  6.882896e+06  3.787044e+10 ...
100047           0.000000  0.000000e+00  0.000000e+00 ...
100048       59810.556774  1.854127e+06  5.067690e+09 ...
100049       48183.296538  6.263829e+05  2.998101e+09 ...
100050           0.000000  0.000000e+00  0.000000e+00 ...
100059           0.000000  0.000000e+00  0.000000e+00 ...
100066           0.000000  0.000000e+00  0.000000e+00 ...
100067       27182.729483  2.364897e+06  3.483892e+08 ...
100075      163587.054375  1.308696e+06  2.757958e+09 ...
100077           0.000000  0.000000e+00  0.000000e+00 ...
100082       16901.607273  1.487341e+06  1.221568e+09 ...
100083           0.000000  0.000000e+00  0.000000e+00 ...
100086       42137.627143  3.539561e+06  1.941943e+09 ...
100090           0.000000  0.000000e+00  0.000000e+00 ...
100100       40102.360851  3.769622e+06  1.249710e+09 ...
100101      183857.184643  2.574001e+06  2.028050e+10 ...
100107       75100.626818  8.261069e+05  2.897578e+09 ...
100109       39472.162975  3.118301e+06  2.695346e+09 ...
100110           0.000000  0.000000e+00  0.000000e+00 ...
100112           0.000000  0.000000e+00  0.000000e+00 ...
100114           0.000000  0.000000e+00  0.000000e+00 ...
100115       46570.500000  4.657050e+04           NaN ...
...                   ...           ...           ... ...
456173      197714.995312  3.163440e+06  3.307257e+10 ...
456178           0.000000  0.000000e+00  0.000000e+00 ...
456186        9984.790385  1.298023e+05  6.373447e+08 ...
456188           0.000000  0.000000e+00  0.000000e+00 ...
456189      133387.442609  3.067911e+06  1.573485e+09 ...
456195           0.000000  0.000000e+00  0.000000e+00 ...
456198      120398.047500  1.155821e+07  4.657981e+09 ...
456199           0.000000  0.000000e+00  0.000000e+00 ...
456201           0.000000  0.000000e+00  0.000000e+00 ...
456206      260434.584205  1.145912e+07  1.109203e+10 ...
456210           0.000000  0.000000e+00  0.000000e+00 ...
456211      136570.500000  1.365705e+05           NaN ...
456213      246443.762647  8.379088e+06  2.345789e+10 ...
456214      391308.138000  1.956541e+06  5.443549e+10 ...
456215        5511.337660  5.180657e+05  6.854465e+08 ...
456217      165277.642737  1.570138e+07  5.056466e+08 ...
456219       72884.079000  7.288408e+05  3.967810e+09 ...
456225      117501.437344  1.128014e+07  6.432464e+09 ...
456233       39394.305000  3.939431e+05  1.426218e+09 ...
456235           0.000000  0.000000e+00  0.000000e+00 ...
456236       22314.458298  2.097559e+06  2.652063e+09 ...
456237       73082.850000  1.096243e+06  4.812742e+09 ...
456239      107540.196648  9.463537e+06  8.113504e+09 ...
456241           0.000000  0.000000e+00  0.000000e+00 ...
456242      148232.328750  1.185859e+06  6.228917e+09 ...
456244      131834.730732  5.405224e+06  3.295703e+10 ...
456246       13136.731875  1.050939e+05  3.335511e+08 ...
456247       23216.396211  2.205558e+06  3.200871e+09 ...
456248           0.000000  0.000000e+00  0.000000e+00 ...
456250      173589.326250  2.083072e+06  1.667716e+08 ...

           NAME_CONTRACT_STATUS_Signed                              \
                                   min max      mean sum       var
SK_ID_CURR
100006                               0   0  0.000000   0  0.000000
100011                               0   0  0.000000   0  0.000000
100013                               0   0  0.000000   0  0.000000
100021                               0   0  0.000000   0  0.000000
100023                               0   0  0.000000   0  0.000000
100028                               0   0  0.000000   0  0.000000
100036                               0   0  0.000000   0  0.000000
100042                               0   0  0.000000   0  0.000000
100043                               0   0  0.000000   0  0.000000
100047                               0   1  0.027778   1  0.027778
100048                               0   0  0.000000   0  0.000000
100049                               0   0  0.000000   0  0.000000
100050                               0   0  0.000000   0  0.000000
100059                               0   0  0.000000   0  0.000000
100066                               0   0  0.000000   0  0.000000
100067                               0   0  0.000000   0  0.000000
100075                               0   0  0.000000   0  0.000000
100077                               0   0  0.000000   0  0.000000
100082                               0   0  0.000000   0  0.000000
100083                               0   0  0.000000   0  0.000000
100086                               0   0  0.000000   0  0.000000
100090                               0   0  0.000000   0  0.000000
100100                               0   1  0.031915   3  0.031229
100101                               0   0  0.000000   0  0.000000
100107                               0   0  0.000000   0  0.000000
100109                               0   0  0.000000   0  0.000000
100110                               0   0  0.000000   0  0.000000
100112                               0   0  0.000000   0  0.000000
100114                               0   0  0.000000   0  0.000000
100115                               0   0  0.000000   0       NaN
...                                ...  ..       ...  ..       ...
456173                               0   0  0.000000   0  0.000000
456178                               0   0  0.000000   0  0.000000
456186                               0   0  0.000000   0  0.000000
456188                               0   0  0.000000   0  0.000000
456189                               0   0  0.000000   0  0.000000
456195                               0   0  0.000000   0  0.000000
456198                               0   0  0.000000   0  0.000000
456199                               0   0  0.000000   0  0.000000
456201                               0   0  0.000000   0  0.000000
456206                               0   0  0.000000   0  0.000000
456210                               0   0  0.000000   0  0.000000
456211                               0   0  0.000000   0       NaN
456213                               0   0  0.000000   0  0.000000
456214                               0   0  0.000000   0  0.000000
456215                               0   0  0.000000   0  0.000000
456217                               0   1  0.042105   4  0.040761
456219                               0   0  0.000000   0  0.000000
456225                               0   0  0.000000   0  0.000000
456233                               0   0  0.000000   0  0.000000
456235                               0   0  0.000000   0  0.000000
456236                               0   0  0.000000   0  0.000000
456237                               0   0  0.000000   0  0.000000
456239                               0   0  0.000000   0  0.000000
456241                               0   0  0.000000   0  0.000000
456242                               0   0  0.000000   0  0.000000
456244                               0   0  0.000000   0  0.000000
456246                               0   0  0.000000   0  0.000000
456247                               0   0  0.000000   0  0.000000
456248                               0   0  0.000000   0  0.000000
456250                               0   0  0.000000   0  0.000000

           NAME_CONTRACT_STATUS_nan
                                min max mean sum  var
SK_ID_CURR
100006                            0   0    0   0  0.0
100011                            0   0    0   0  0.0
100013                            0   0    0   0  0.0
100021                            0   0    0   0  0.0
100023                            0   0    0   0  0.0
100028                            0   0    0   0  0.0
100036                            0   0    0   0  0.0
100042                            0   0    0   0  0.0
100043                            0   0    0   0  0.0
100047                            0   0    0   0  0.0
100048                            0   0    0   0  0.0
100049                            0   0    0   0  0.0
100050                            0   0    0   0  0.0
100059                            0   0    0   0  0.0
100066                            0   0    0   0  0.0
100067                            0   0    0   0  0.0
100075                            0   0    0   0  0.0
100077                            0   0    0   0  0.0
100082                            0   0    0   0  0.0
100083                            0   0    0   0  0.0
100086                            0   0    0   0  0.0
100090                            0   0    0   0  0.0
100100                            0   0    0   0  0.0
100101                            0   0    0   0  0.0
100107                            0   0    0   0  0.0
100109                            0   0    0   0  0.0
100110                            0   0    0   0  0.0
100112                            0   0    0   0  0.0
100114                            0   0    0   0  0.0
100115                            0   0    0   0  NaN
...                             ...  ..  ...  ..  ...
456173                            0   0    0   0  0.0
456178                            0   0    0   0  0.0
456186                            0   0    0   0  0.0
456188                            0   0    0   0  0.0
456189                            0   0    0   0  0.0
456195                            0   0    0   0  0.0
456198                            0   0    0   0  0.0
456199                            0   0    0   0  0.0
456201                            0   0    0   0  0.0
456206                            0   0    0   0  0.0
456210                            0   0    0   0  0.0
456211                            0   0    0   0  NaN
456213                            0   0    0   0  0.0
456214                            0   0    0   0  0.0
456215                            0   0    0   0  0.0
456217                            0   0    0   0  0.0
456219                            0   0    0   0  0.0
456225                            0   0    0   0  0.0
456233                            0   0    0   0  0.0
456235                            0   0    0   0  0.0
456236                            0   0    0   0  0.0
456237                            0   0    0   0  0.0
456239                            0   0    0   0  0.0
456241                            0   0    0   0  0.0
456242                            0   0    0   0  0.0
456244                            0   0    0   0  0.0
456246                            0   0    0   0  0.0
456247                            0   0    0   0  0.0
456248                            0   0    0   0  0.0
456250                            0   0    0   0  0.0

[103558 rows x 140 columns]

In [36]:
cc_agg.columns = pd.Index(['CC_' + e[0] + "_" + e[1].upper() for e in cc_agg.columns.tolist()])
cc_agg.columns

Index(['CC_MONTHS_BALANCE_MIN', 'CC_MONTHS_BALANCE_MAX',
       'CC_MONTHS_BALANCE_MEAN', 'CC_MONTHS_BALANCE_SUM',
       'CC_MONTHS_BALANCE_VAR', 'CC_AMT_BALANCE_MIN', 'CC_AMT_BALANCE_MAX',
       'CC_AMT_BALANCE_MEAN', 'CC_AMT_BALANCE_SUM', 'CC_AMT_BALANCE_VAR',
       ...
       'CC_NAME_CONTRACT_STATUS_Signed_MIN',
       'CC_NAME_CONTRACT_STATUS_Signed_MAX',
       'CC_NAME_CONTRACT_STATUS_Signed_MEAN',
       'CC_NAME_CONTRACT_STATUS_Signed_SUM',
       'CC_NAME_CONTRACT_STATUS_Signed_VAR', 'CC_NAME_CONTRACT_STATUS_nan_MIN',
       'CC_NAME_CONTRACT_STATUS_nan_MAX', 'CC_NAME_CONTRACT_STATUS_nan_MEAN',
       'CC_NAME_CONTRACT_STATUS_nan_SUM', 'CC_NAME_CONTRACT_STATUS_nan_VAR'],
      dtype='object', length=140)

### Count credit card lines

In [37]:
cc_agg['CC_COUNT'] = cc.groupby('SK_ID_CURR').size()
cc_agg['CC_COUNT']

In [38]:
del cc

In [39]:
gc.collect()

105